#96 [ui, fix] todo 추가 뷰, 기능 구현
Hous-Release/hous-AOS pull request #102
Opened 2022-11-01 17:29 UTC by murjune

## 관련 이슈
- closed #96 

## 작업한 내용
- todo 추가 뷰 컴포즈 구현
- todo 버튼 활성화 기능 구현
- backbutton 클릭시 out 다이얼로그 기능 구현

## PR 포인트
- 인생 첫 컴포즈뷰입니다 리뷰 잘 부탁드려용 ㅎ ㅎ ㅎ@KWY0218   
- 아마 수정뷰랑 UiState가 똑같을 것 같아서 ToDoUiState를 추상클래스로 만들었는데 괜찮은 방식일라나요..?? 사실 AddToDoViewModel도 서버 통신하는 부분 빼면 로직이 거의 동일할 것 같아서 ToDoViewModel이라는 인터페이스 하나 만들어서 추상화하고 싶기도하고.. 근데 좀 투머치인 것 같기도 하고.. 하핫

2022-11-02 05:59 UTC, KWY0218 requested changes
컴포즈로 작업 하시느라 수고하셨습니다!!!
처음 치고는 정말 잘 한 것 같습니다!! ^__^
viewmodel copy 하는 로직 마싯네요 ~ ^__^ 다음에 쇽샥 하겠습니다~

2022-11-02 05:59 UTC, KWY0218 commented on app/src/main/java/hous/release/android/util/component/ToDoUserScreen.kt
> +    }
[내 코드 ^__^](https://github.com/TeamHous/Hous-Android/blob/develop/app/src/main/java/com/hous/hous_aos/ui/newrules/NewRulesScreen.kt) 를 보면 
LazyColumn `.wight(1f)` 를 하면 Row를 감쌀 필요 없이 ToDoButton만으로 버튼을 맨 하단에 놓을 수 있습니다

2022-11-02 05:59 UTC, KWY0218 commented on app/src/main/java/hous/release/android/util/component/ToDoUserScreen.kt
> +}
비즈니스 로직 같아 보입니다..!
viewmodel로 옮기는 것이 어떨까요..?

2022-11-02 05:59 UTC, KWY0218 commented on app/src/main/java/hous/release/android/util/extension/LifecycleExtension.kt
> +}
ㅠㅠ 머지되면 저도 수정하겠읍니다... 😭

2022-11-02 05:59 UTC, KWY0218 commented on app/src/main/java/hous/release/android/util/component/DayItem.kt
> +) {
파일 명 `DayItem` 말고 `DayItems` 라고 수정 후 해당 함수는 private 으로 만들어도 좋을 것 같습니다

2022-11-02 05:59 UTC, KWY0218 commented on app/src/main/java/hous/release/android/util/component/DayItem.kt
> +    dayNameList: List<String> = listOf("월", "화", "수", "목", "금", "토", "일")
`stringArray` 를 사용하면 좋을 것 같습니다

2022-11-02 05:59 UTC, KWY0218 commented on app/src/main/java/hous/release/android/util/component/DayItem.kt
> +        }
```suggestion
        Box(
            modifier = Modifier
                .clip(CircleShape)
                .background(color = colorResource(id = if(isSelected) R.color.hous_blue_l1 else R.color.hous_blue_l1))
                .clickable {
                    selectTodoDay(userIdx, dayIdx)
                    hideKeyBoard()
                }
                .size(40.dp),
            contentAlignment = Alignment.Center
        ) {
            Text(
                text = text,
                color = colorResource(id = if(isSelected) R.color.hous_blue else R.color.hous_blue),
                style = b3.copy(
                    fontSize = dpToSp(dp = 13.dp)
                )
            )
        }
```
이런 식으로 하면 아래 코드를 줄일 수 있을 것 같습니다

2022-11-02 05:59 UTC, KWY0218 commented on app/src/main/java/hous/release/android/util/component/ToDoUserItem.kt
> +                .padding(bottom = 12.dp),
```suggestion
                .padding(start = 3.dp, top = 15.dp, bottom = 12.dp),
```
이렇게 할 수도 있습니다

2022-11-02 05:59 UTC, KWY0218 commented on app/src/main/java/hous/release/android/util/component/ToDoUserItem.kt
> +            if (todoUser.isChecked) {
이 로직도 코드 중복된 곳은 놔두고, 로직이 변경되는 부분만 위에 코멘트 남긴 것 처럼 if 문을 쓰면 코드 중복을 줄일 수 있을 것 같습니다

2022-11-02 05:59 UTC, KWY0218 commented on app/src/main/java/hous/release/android/util/component/ToDoUserItem.kt
> +}
@Hous-Release/android 
이 부분 저도 쓰는데, HomyType enum class 내에 확장함수로 하나 만드는 거 어떤가요??

2022-11-02 05:59 UTC, KWY0218 commented on app/src/main/java/hous/release/android/util/component/ToDoUserProfile.kt
> +            }
```suggestion
            )
```
없애줘잉

2022-11-02 05:59 UTC, KWY0218 commented on app/src/main/java/hous/release/android/util/component/ToDoUserProfile.kt
> +                .padding(end = 7.dp),
```suggestion
                .padding(start = 6.dp, end = 7.dp)
```

2022-11-02 05:59 UTC, KWY0218 commented on app/src/main/java/hous/release/android/util/component/ToDoUserProfile.kt
> +                ),
ㅋㅋㅋㅋ theme 추가하기 귀찮긴 해~~

2022-11-02 05:59 UTC, KWY0218 commented on app/src/main/java/hous/release/android/util/component/ToDoUserProfile.kt
> +                    .padding(bottom = 3.dp)
```suggestion
                    .padding(top = 5.dp, bottom = 3.dp)
```

2022-11-02 05:59 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/todo/viewmodel/UpdateToDoViewModel.kt
> +            )
해당 로직에서 `selectedUsers` 도 copy 해야 되는 이유가 있을까요..?

2022-11-02 05:59 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/todo/add/AddToDoFragment.kt
> +    }
setOnTouchListenter 랑 setOnClickListener랑 어느 부분에서 다른건가요..?

isChecked 랑 isSelected 같은 느낌이려나..?

2022-11-02 05:59 UTC, KWY0218 commented on app/src/main/java/hous/release/android/util/component/ToDoUserScreen.kt
> +            )
```suggestion
            if(uiState.selectedUsers.isEmpty()){
                ToDoUserProfiles(selectedUsers = uiState.selectedUsers)            
            }
```
컴포넌트 안에 visibilty를 구분하는 flag를 넣는 것 보다 screen에 넣는 것이 screen 함수를 읽으면서
아 selectedUser가 비어 있으면 이 컴포넌트는 안 보이는 구나~
하며 이해하기 더 좋을 것 같다는 개인적인 생각입니다!

2022-11-02 05:59 UTC, KWY0218 commented on app/src/main/java/hous/release/android/util/component/ToDoUserProfile.kt
> +            Spacer(modifier = Modifier.size(11.dp))
위 코멘트처럼 로직을 만들면 screen 내에 있는 if문 내에 spacer를 넣으면 위 Column은 없애고, LazyRow만 남길 수 있을 것 같습니다

2022-11-02 05:59 UTC, KWY0218 commented on app/src/main/java/hous/release/android/util/component/ToDoUserProfile.kt
> +    ) {
위 부분도 Row modifier 내에서 `.background` , `.clip` 을 통해서 구현할 수 있습니다..!
~대충 `Surface` 없애도 된다는 코리~

2022-11-02 07:15 UTC, 2zerozu approved these changes
컴포즈라니... 멋있습니다

2022-11-02 07:15 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
>      }
고맙습니다 ㅎㅎ.. 원용이가 #99 에 수정해놔서 머지하면 충돌날 수도 있겠네요

+근데 `intent.putExtra`하면 `startActivity` 안 해줘도 액티비티 실행되나요??

2022-11-02 07:15 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/todo/add/AddToDoFragment.kt
> +    }
👍🏻

2022-11-02 07:15 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/todo/add/AddTodoUserScreen.kt
> +@Composable
shit.........

2022-11-02 07:15 UTC, 2zerozu commented on app/src/main/res/layout/fragment_add_to_do.xml
> +            android:id="@+id/btn_add_to_do_back"
아 imageview여도 btn으로 변수명 해도 되는군요...
저도 수정갈길게요

2022-11-02 07:19 UTC, KWY0218 commented on app/src/main/res/layout/fragment_add_to_do.xml
> +            android:id="@+id/btn_add_to_do_back"
엥 안되지 않나요?? 나 무조건 iv로 했는데...?

2022-11-02 07:19 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
>      }
이거 그냥 실행 안 하려고 없앤듯요

2022-11-02 13:42 UTC, yjooooo requested changes
고생하셨습니다!!

2022-11-02 13:42 UTC, yjooooo commented on app/src/main/AndroidManifest.xml
> +            android:screenOrientation="portrait"
구우욷

2022-11-02 13:42 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
> +        val intent = Intent(requireActivity(), PersonalityResultActivity::class.java)
저희 저번에 인텐트에 담는 게 없다면 한줄로 startActivity(Intent(...)), 
담는게 있거나 추가 설정이 있다면 apply로 하기로 했던 게 기억나서 달아놓습니다!

2022-11-02 13:42 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/todo/add/AddToDoFragment.kt
> +        setStatusBarColor(colorRes = R.color.hous_white)
제가 themes.xml에 statusbar컬러를 모든 화면에 white로 설정해놨는데 또 설정한 이유가 있을까요?

2022-11-02 13:42 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/todo/add/AddToDoFragment.kt
> +    }
themes.xml에 모든 화면 statusbar컬러 white로 설정했습니다!

2022-11-02 13:42 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/todo/add/AddToDoVIewModel.kt
> +        delay(500L)
딜레이를 준 이유가 있을까요?

2022-11-02 13:42 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/todo/add/AddToDoVIewModel.kt
> +                )
뽀짝 귀엽쟈나

2022-11-02 13:42 UTC, yjooooo commented on app/src/main/java/hous/release/android/util/component/DayItem.kt
> +        }
둘다 믓지다

2022-11-03 07:47 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/todo/add/AddToDoFragment.kt
> +                hideKeyBoard = ::hideKeyBoard
아니요 없어요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2022-11-03 07:48 UTC, murjune commented on app/src/main/java/hous/release/android/util/component/ToDoUserScreen.kt
> +    ) {
저번에 그렇게 했었는데 LazyColumn내 item들 클릭시에는 안내려가더라구요.. ㅜㅜㅜ  
그래도 다시 한번 해보겠습니당..

2022-11-03 07:48 UTC, murjune commented on app/src/main/java/hous/release/android/util/component/ToDoUserScreen.kt
> +            LazyColumn() {
엇..

2022-11-03 07:50 UTC, murjune commented on app/src/main/java/hous/release/android/util/component/ToDoUserScreen.kt
> +}
얘 왜 안옮겼냐.. 수정하겠습니다!!

2022-11-03 07:51 UTC, murjune commented on app/src/main/java/hous/release/android/util/component/ToDoUserScreen.kt
> +    }
얍얍

2022-11-03 07:51 UTC, murjune commented on app/src/main/java/hous/release/android/util/extension/LifecycleExtension.kt
> +}
히히히히

2022-11-03 07:51 UTC, murjune commented on app/src/main/java/hous/release/android/util/component/DayItem.kt
> +) {
얍얍!!

2022-11-03 07:52 UTC, murjune commented on app/src/main/java/hous/release/android/util/component/DayItem.kt
> +    dayNameList: List<String> = listOf("월", "화", "수", "목", "금", "토", "일")
아 딱 들켰네.. ㅋㅋㅋㅋㅋㅋㅋ

2022-11-03 07:52 UTC, murjune commented on app/src/main/java/hous/release/android/util/component/DayItem.kt
> +        }
오오오옹  갓워뇽

2022-11-03 07:52 UTC, murjune commented on app/src/main/java/hous/release/android/util/component/ToDoUserItem.kt
> +                .padding(bottom = 12.dp),
이건 몰랐네 ㄷ ㄷ ㄷ

2022-11-03 07:53 UTC, murjune commented on app/src/main/java/hous/release/android/util/component/ToDoUserItem.kt
> +            if (todoUser.isChecked) {
해보겠습니다!!

2022-11-03 07:53 UTC, murjune commented on app/src/main/java/hous/release/android/util/component/ToDoUserItem.kt
> +}
제가 넣어 둘게요~~

2022-11-03 07:53 UTC, murjune commented on app/src/main/java/hous/release/android/util/component/ToDoUserProfile.kt
> +            }
알겠어잉~

2022-11-03 07:54 UTC, murjune commented on app/src/main/java/hous/release/android/util/component/ToDoUserProfile.kt
> +                ),
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 풀받고 수정할게~~~

2022-11-03 07:57 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/todo/viewmodel/UpdateToDoViewModel.kt
> +            )
어 지워도 되겠네 예리하시네용~ 👍 👍

2022-11-03 07:59 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/todo/add/AddToDoFragment.kt
> +    }
여기서는 그냥 똑같은 느낌이긴한데 ㅋㅋㅋㅋ  
제가 알기로는 Touch는 Action같은거 지정할 수 있는걸로 알고 있습니다.  
드래그나 swipe같은거로 이벤트 처리할 수 있을껄요?? (안해보긴 했음.. ㅋㅋㅋㅋ)

2022-11-03 08:00 UTC, murjune commented on app/src/main/java/hous/release/android/util/component/ToDoUserScreen.kt
> +            )
오 그게 더 좋겠네요 배워갑니당~

2022-11-03 08:02 UTC, murjune commented on app/src/main/java/hous/release/android/util/component/ToDoUserProfile.kt
> +    ) {
> 대충 Surface 없애도 된다는 코리  
ㅋㅋㅋㅋㅋ 화기인~

2022-11-03 08:02 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
>      }
> 이거 그냥 실행 안 하려고 없앤듯요  
ㅋㅋㅋㅋ 맞습니다

2022-11-03 08:02 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
>      }
> 이거 그냥 실행 안 하려고 없앤듯요  
ㅋㅋㅋㅋ 맞습니다

2022-11-03 08:03 UTC, murjune commented on app/src/main/res/layout/fragment_add_to_do.xml
> +            android:id="@+id/btn_add_to_do_back"
> 저도 ImageButton의 경우에는 btn으로 갔는데 ImageView는 iv로 갔습니다!
혹시 이부분 백버튼이라면 ImageButton으로 해주세요!

ImageView : 클릭 안되는 이미지
ImageButton : 클릭 이벤트있는 이미지
로 가면 좋을 것 같아요!  

바꿀게연...

2022-11-03 08:04 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
> +        val intent = Intent(requireActivity(), PersonalityResultActivity::class.java)
제가 만든게 아니긴합니다 ㅋㅋㅋㅋㅋㅋㅋ 히힣

2022-11-03 08:07 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/todo/add/AddToDoFragment.kt
> +        setStatusBarColor(colorRes = R.color.hous_white)
![image](https://user-images.githubusercontent.com/87055456/199672256-5b2b4ab4-1d51-474a-a033-b8a127de6eaf.png)  

원용이가 여기서 바꿔줬더라구요  
여기서 statusbar 색이 바뀌어서 제 AddToDoFragment에서 statusbar 색을 바꿔줘야합니당

2022-11-03 08:07 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/todo/add/AddToDoVIewModel.kt
> +        delay(500L)
실제 서버 통신할 때 약간의 delay가 있으니까 테스트할 때 넣어준겁니당 ㅎ ㅎ ㅎ  
서버 연결하면 없어질 녀석!!

2022-11-03 08:07 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/todo/add/AddToDoVIewModel.kt
> +                )
헤헷

2022-11-03 09:34 UTC, murjune commented on app/src/main/java/hous/release/android/util/component/ToDoUserScreen.kt
> +    ) {
ㅜㅜ.. 안되네요

2022-11-03 09:47 UTC, murjune commented on app/src/main/java/hous/release/android/util/component/ToDoUserScreen.kt
> +    }
근데 저는 LazyColumn이 `weight(1f)`로 하면 안되는게 LazyColumn 위에 UI들은 스크롤이 되면 안되거덩요..  
그래서 `.wight(1f)`를 쓰기 쉽지 않을 것 같습니다!!

2022-11-03 10:12 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/todo/viewmodel/UpdateToDoViewModel.kt
> +            )
아 이 부분이 빠지면 buttonState가 안바뀌네요.. 있어야합니다!!

2022-11-03 10:24 UTC, murjune commented on app/src/main/java/hous/release/android/util/component/ToDoUserItem.kt
> +}
@KWY0218 HomyType이 domain에 있어서 `R`을 참조할 수가 없네용.. util에 확장함수 만드는 것이 좋을 듯 합니당

2022-11-03 11:54 UTC, murjune commented
noRippleClickable 확장함수를 만들어서 사용해도 될 것 같아서 사용하려했는데..  
계속 오류가 떠서 ㅜㅜ 일단 기존 방식인 `val interactionSource = remember { MutableInteractionSource() }`을 만들어서 클릭시 ripple을 없앴습니다.  
https://github.com/Hous-Release/hous-AOS/pull/102/commits/21a3161cf713bc88af06955bd7bbf05b8272f515

2022-11-03 13:29 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/todo/add/AddToDoFragment.kt
> +        setStatusBarColor(colorRes = R.color.hous_white)
아아 모든 화면의 statusbar색상을 흰색으로 통일하는 줄 알았는데 아닌가보네요?

2022-11-03 13:30 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/todo/add/AddToDoVIewModel.kt
> +        delay(500L)
아아아! 오케이!

2022-11-03 14:45 UTC, yjooooo approved these changes
구욷!!!!

2022-11-03 18:32 UTC, merged