#95 [ui, feat] ProfileEdit 뷰, 서버 구현
Hous-Release/hous-AOS pull request #114
Opened 2022-11-06 20:30 UTC by 2zerozu

## 관련 이슈
- closed #이슈넘버

## 작업한 내용
- 

## PR 포인트
-

2022-11-07 06:18 UTC, KWY0218 requested changes
`parcelable` plugin이 kotlin 이라서 순수 코틀린인 줄 알았는데, 찾아보니 안드로이드 종속성이 있더라고요.. 그래서 이용하기 위해선 ui layer에 parcelable 객체를 만들어서 보내야 할 것 같습니다...!

2022-11-07 10:02 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/profile/ProfileEditActivity.kt
> +                !binding.ivProfileEditBirthdayCheck.isSelected
with(bind)로 묶는다면 !bind는 어떻게 처리하나요? tv어쩌고 앞에다가 !해주나요?

2022-11-07 10:45 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/profile/ProfileEditActivity.kt
> +                !binding.ivProfileEditBirthdayCheck.isSelected
네~

2022-11-08 13:29 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/login/UserInputViewModel.kt
> +    var isPrivateBirthday = MutableLiveData(false)
> var 로 바꾼 이유가 있을까요....?

아 이것저것 해보다가 바꼈나보네요 되돌려두겠숨

2022-11-09 08:38 UTC, murjune approved these changes
고생하셨습니다 :D   
함께 논의할 내용 comment 달았으니 봐주세열~~ (일단 approve 드렸습니다 ㅋㅋㅋ)

2022-11-09 08:38 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
> +        const val NO_DATA = -1
👍 👍

2022-11-09 08:38 UTC, murjune commented on app/src/main/res/layout/activity_personality_result.xml
> +            android:id="@+id/btn_personality_result_back"
ImageButton으로 바꿔주세영

2022-11-09 08:38 UTC, murjune commented on app/src/main/res/layout/activity_personality_result.xml
> +            android:id="@+id/btn_personality_result_complete"
ClickEvent있는 textView라 Id를 btn으로 하신 것 같은데 이 부분은 저희 얘기를 안한 것 같아서요!! 함께 정해보아요~
@2zerozu @KWY0218 @yjooooo

2022-11-09 08:38 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
> +            if (profile.introduction.isNullOrEmpty()) {
```suggestion
            if (profile.introduction.isNullOrBlank()) {
```
introduction에 `" "` 같은 blank가 들어갈 수 있으니 `isNullOrBlank` 추천합니다!!

2022-11-09 08:38 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/profile/ProfileViewModel.kt
> +    }
onResume()에서 getProfile()을 호출하는 걸로 아는데 빼도 되지 않으려나..??  
사실 저도 이렇게 하긴 했는데.. 여러분들의 의견이 궁금합니다!!  
@2zerozu @KWY0218 @yjooooo

2022-11-09 08:38 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditActivity.kt
> +                Timber.e("$birthdayInt")
지워도 되는 Timber인 것 같습니다!!

2022-11-09 08:38 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditActivity.kt
> +        Timber.e("$year, $month, $day")
얘도 지워도 될 것 같아요~

2022-11-09 08:38 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditActivity.kt
> +        val birthdayList: List<String> = birthday.split(SLASH)
제 개인적인 생각인데 `split("/")` 가 다른 사람이 봤을 때 더 알아보기 편한 것 같습니다!!

2022-11-09 08:38 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditActivity.kt
> +        Timber.e("$year, $month, $day")
```suggestion
    private fun initDateFormatToInt(birthday: String) = birthday.split("/").map { it.toInt() }
```  
위와 같이 코드를 줄일 수도 있겠습니다.

2022-11-09 08:38 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditViewModel.kt
> +    private val _isBirthdayPublic = MutableLiveData(false)
```suggestion
    private val isBirthdayPublic = MutableLiveData(false)
```  
여기서는 `backing`을 안해줘도 될 것 같습니다

2022-11-09 09:10 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditActivity.kt
> +        Timber.e("$year, $month, $day")
> 얘도 지워도 될 것 같아요~

얘두

2022-11-09 09:11 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditActivity.kt
> +        val birthdayList: List<String> = birthday.split(SLASH)
> 제 개인적인 생각인데 `split("/")` 가 다른 사람이 봤을 때 더 알아보기 편한 것 같습니다!!

아 이건 상수 안 써도 되는 건가요?

2022-11-09 09:14 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/profile/ProfileViewModel.kt
> +    }
> onResume()에서 getProfile()을 호출하는 걸로 아는데 빼도 되지 않으려나..?? 사실 저도 이렇게 하긴 했는데.. 여러분들의 의견이 궁금합니다!! @2zerozu @KWY0218 @yjooooo

![image](https://user-images.githubusercontent.com/84129098/200789334-9725c738-5c2d-4a82-8897-95b95c13065f.png)

빼도 될 것 같기도...?

2022-11-09 09:15 UTC, 2zerozu commented on app/src/main/res/layout/activity_personality_result.xml
> +            android:id="@+id/btn_personality_result_back"
> ImageButton으로 바꿔주세영

file change로 본 거 아녀?? 어케 찾았대요... 굿굿

2022-11-09 13:06 UTC, yjooooo approved these changes
수고하셨습니다!

2022-11-09 13:06 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/profile/ProfileViewModel.kt
> +    }
resume에서 하면 뷰모델 init과 뷰의 oncreate나 onviewCreated에서 호출하지 않아도 될 것 같습니다.
또한 저는 뷰모델의 init에서 api를 호출하는 것을 선호하지 않습니다, 뷰에서 어떤 api를 호출하여 어떤 내용을 띄우는지 알기 어려워서요!

2022-11-09 13:06 UTC, yjooooo commented on app/src/main/res/layout/activity_personality_result.xml
> +            android:id="@+id/btn_personality_result_complete"
저는 tv요~! 뷰 이름 따라가는게 일관성있는 것 같습니다!

2022-11-09 13:06 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditActivity.kt
> +        val birthdayList: List<String> = birthday.split(SLASH)
이부분은 "/"가 가독성은 좋아보이는데 하드코딩 느낌이 나기도 하고? 코드 주인의 의견을 따라가겠습니다!

2022-11-09 13:30 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditActivity.kt
> +        val birthdayList: List<String> = birthday.split(SLASH)
그럼 가독성으로 가겠숨다

2022-11-09 19:08 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditActivity.kt
> +        Timber.e("$year, $month, $day")
이렇게 줄이니까 터지네요..

2022-11-10 05:20 UTC, KWY0218 approved these changes
수고하셨습니다 ~ 👍

2022-11-10 05:21 UTC, merged