[ui/feat] #121 호미프로필 ui/api 구현
Hous-Release/hous-AOS pull request #125
Opened 2022-11-09 18:58 UTC by 2zerozu

## 관련 이슈
- closed #121

https://user-images.githubusercontent.com/84129098/200917247-fae8c9e6-7e61-4f36-aafd-b77a2ea24b77.mov

## 작업한 내용
- 호미프로필 ui/api 구현

## PR 포인트
- 뱃지 이미지 가생이가 투명색이 아니라 이미지 변경 후 다시 확인해봐야함

2022-11-10 07:13 UTC, KWY0218 requested changes
작업하시느라 수고하셨습니다 ~ !

2022-11-10 07:13 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/hous/HousFragment.kt
> +    private fun onClickHomie(position: Int) {
postion 말고 adapter 내에 `onBind` 내에 들어오는 `homy` 를 넘겨주면 더 깔끔할 거 같아요..!

2022-11-10 07:13 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/profile/homie/HomieProfileViewModel.kt
> +            getHomieProfileUseCase.invoke(homieId.value!!)
```suggestion
            getHomieProfileUseCase(homieId.value!!)
```
.invoke 빼도 됩니다..!

2022-11-10 07:13 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/profile/homie/HomieProfileViewModel.kt
> +    private val homieId = MutableLiveData<Int>()
첫 init 때만 사용하고 사용 안 하는 것 같은데 따로 변수로 저장해야 될 이유가 있을까요?

2022-11-10 07:13 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/profile/homie/HomieProfileActivity.kt
> +        homieProfileViewModel.getHomieProfile()
특별한 이유가 없다면 `initHomieId` 함수는 삭제하고, getHomieProfile 파라미터를 추가하면 좋을 것 같습니다

2022-11-10 11:48 UTC, murjune approved these changes
고생하셨습ㄴ다 👍

2022-11-10 11:48 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/profile/homie/HomieProfileActivity.kt
> +        private val DEFAULT = -1
상수 네이밍을 좀더 구체적으로 써주세용~

2022-11-10 11:48 UTC, murjune commented on app/src/main/java/hous/release/android/util/binding/BindingAdapters.kt
> +    @BindingAdapter("visibility")
`app:textViewVisiblity` 와 같이 좀 더 구체적으로 바꿔줘요~

2022-11-11 08:55 UTC, yjooooo approved these changes
고생하셨습니다!

2022-11-13 11:42 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/profile/homie/HomieProfileViewModel.kt
> +    private val homieId = MutableLiveData<Int>()
> 첫 init 때만 사용하고 사용 안 하는 것 같은데 따로 변수로 저장해야 될 이유가 있을까요?

없어서 수정했습니다요

2022-11-13 12:00 UTC, KWY0218 approved these changes
작업하시느라 수고하셨습니다 ~ 😄

2022-11-13 12:10 UTC, merged