[fix] #122 레포지토리 대신 유즈케이스로 변경, 성향테스트 컬러값 로직 구현
Hous-Release/hous-AOS pull request #126
Opened 2022-11-09 20:02 UTC by 2zerozu

## 관련 이슈
- closed #122

## 작업한 내용
- 

## PR 포인트
-

2022-11-10 07:18 UTC, KWY0218 requested changes
작업하시느라 수고하셨습니다 ~ ~ 👍

2022-11-10 07:18 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/login/LoginViewModel.kt
> +            postLoginUseCase.invoke(
usecase 사용할 때 invoke 빼도 됩니다... 😭

2022-11-10 07:18 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/personality/result/PersonalityResultViewModel.kt
> +    }
여기도 해당 컬러를 변수로 가지고 있을 필요가 있는지 궁금합니다...!

2022-11-10 07:18 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/personality/result/PersonalityResultActivity.kt
> +    }
companion object 나도 이번에 추가했는데 아마 충돌 날듯.. 먼저 머지 되는 사람꺼로 하기로 ~ ~

2022-11-10 11:51 UTC, murjune approved these changes
궁금한 점은 원용이와 같습니당 ㅋㅋㅋ  
그 외에는 없네요 고생하셨습니다 :D

2022-11-11 11:55 UTC, yjooooo approved these changes
고생하셨어요!

2022-11-11 16:12 UTC, KWY0218 approved these changes
작업하시느라 수고하셨습니다~! 👍

2022-11-11 16:58 UTC, merged