#123 [ui/fix]
Hous-Release/hous-AOS pull request #132
Opened 2022-11-13 16:48 UTC by 2zerozu

## 관련 이슈
- closed #이슈넘버

## 작업한 내용
- 

## PR 포인트
-

2022-11-14 05:11 UTC, KWY0218 approved these changes
저는 로직 괜찮다고 생각합니다 ~ LGTM ~ 👍

2022-11-14 06:33 UTC, yjooooo approved these changes
저도 BindingAdapter에서 처리하는 거 좋습니다!

2022-11-14 08:50 UTC, yjooooo commented on app/src/main/java/hous/release/android/util/binding/BindingAdapters.kt
> +    @BindingAdapter("lottie_color", "badge")
```kotlin
@BindingAdapter(value = ["lottie_color", "badge"], requireAll = true)
```
이부분 이렇게 바꿔주시고 playAnimation() 한번 빼보시겠어요?
그러면 autoPlay가 잘 동작할 수도 있을 것 같아요!
저는 BindingAdapter써도 autoPlay가 잘 동작해요!

2022-11-14 09:28 UTC, yjooooo requested changes
처음 리뷰할때 꼼꼼히 못봐서 죄송합니다 ㅜㅜ

2022-11-14 09:28 UTC, yjooooo commented on app/src/main/java/hous/release/android/util/binding/BindingAdapters.kt
> +    fun LottieAnimationView.lottie_fileName(color: String?, badge: String?) {
여기 함수명 carmelCase로 써주셔야 할 것 같아요

2022-11-14 09:32 UTC, KWY0218 commented on app/src/main/java/hous/release/android/util/binding/BindingAdapters.kt
> +    fun LottieAnimationView.lottie_fileName(color: String?, badge: String?) {
와 이걸 못 봤네 👍 👍

2022-11-14 10:11 UTC, yjooooo commented on app/src/main/java/hous/release/android/util/binding/BindingAdapters.kt
> +    fun LottieAnimationView.lottie_fileName(color: String?, badge: String?) {
Line127도 위의 코드들은 카멜케이스로 써서 통일하는게 좋을 것 같아요!

2022-11-14 10:15 UTC, yjooooo requested changes

2022-11-14 10:15 UTC, yjooooo commented on app/src/main/java/hous/release/android/util/binding/BindingAdapters.kt
> +    fun LottieAnimationView.backgrund(color: String?) {
여기 오타 났어요!

2022-11-14 10:22 UTC, 2zerozu commented on app/src/main/java/hous/release/android/util/binding/BindingAdapters.kt
> +    fun LottieAnimationView.lottie_fileName(color: String?, badge: String?) {
와 내가 왜 그랬지.. 졸면서 해서 ㅎ 확인이용

2022-11-14 10:48 UTC, murjune approved these changes
고생하셨습니다~!~!  로티 쓰는 거 나중에 쏙샥할게요!

2022-11-17 12:46 UTC, yjooooo approved these changes

2022-11-17 12:52 UTC, merged