Feature/#138 setting firebase
Hous-Release/hous-AOS pull request #144
Opened 2022-11-22 10:54 UTC by KWY0218

## 관련 이슈
- closed #138 

https://user-images.githubusercontent.com/82709044/203296129-53b74a7e-ddfa-4eca-9854-664c81a51873.mp4

## 작업한 내용
1. firebase 애널리틱스 앱 진입만 전송
2. 성향 테스트 결과 로딩 로티 교체
3. 성향 테스트 클릭 디바운스 적용
4. 성향 테스트 점수 합산 방식 변경
5. 성향 테스트 이후 애니메이션 나오게 수정
6. 푸시 알림 pending intent 추가 

## PR 포인트
1. 아요도 앱 진입만 심었다길래 앱 진입만 넣었습니다.
2. 성향 테스트 점수 합산 방식 바꿨는데, 피드백 받습니다.
3. 빠르게 클릭하면 성향 테스트 입력이 잘 안되는 부분 아예 디바운스 300ms 줬습니다. (영주가 보내 준 코드 보고 떠올림 ㄳ ㄳ)
4. 푸시 알림 클릭하면 앱 안 켜지길래 pending intent 추가했습니다. 그런데 앱이 켜져있을 때에도 클릭하면 스플래쉬가 띄어지는데 이 플로우가 자연스러운건지 헷갈립니다.

2022-11-22 16:00 UTC, 2zerozu approved these changes
고생해쏘 ~~~ LGTM

2022-11-22 16:00 UTC, 2zerozu commented on app/src/main/res/layout/item_personality_test_loading.xml
> +        android:layout_height="220dp"
👍🏻

2022-11-22 22:08 UTC, murjune approved these changes
고생 많았습니당 ~~ 근데 저도 loading.json 이라고 네이밍했는데.. 한명은 이름 바꿔야할듯~~

2022-11-22 22:08 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/personality/test/PersonalityTestViewModel.kt
> +        )
HashMap이 좋긴해~

2022-11-23 00:57 UTC, KWY0218 commented
@murjune 
둘 다 똑같은 로티라 괜춘할 거 같습니당 ~

2022-11-23 07:03 UTC, yjooooo requested changes
1. 좋아요
2. 👍
3. 👍
4. 이부분은 이번 릴리즈에는 처리하지 않기로 한 것 같아서 나중에 추가하면 될 것 같습니다! 스파크도 업데이트때 해결했습니다!

2022-11-23 07:03 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/personality/test/PersonalityTestViewModel.kt
> +        15 to TestHolder()
어차피 같은 TestHolder고 배열과 다른 점은 index+1 인데 배열로 하면 코드가 더 깔끔할 수도 있지 않을까요?
아니면 HashMap을 쓰고 싶다면 이렇게 쓰면 어떨까요?
```kotlin 
val testScore: HashMap<Int, TestHolder> = HashMap<Int, TestHolder>().apply {
            for (i in 1..15) {
                put(i, TestHolder())
            }
        }
```

2022-11-23 08:49 UTC, yjooooo approved these changes
고생하셨습니다!!

2022-11-23 13:48 UTC, merged