[fix] #153 fix to do update
Hous-Release/hous-AOS pull request #156
Opened 2022-12-04 18:34 UTC by murjune

## 관련 이슈
- closed #이슈넘버

## 작업한 내용
- 

## PR 포인트
-

2022-12-05 00:11 UTC, KWY0218 approved these changes
좋아유~ 😄👍

2022-12-05 02:50 UTC, 2zerozu approved these changes
고생하셨숨둥ㅇ~~~

2022-12-05 05:06 UTC, yjooooo approved these changes
고생하셨습니다!!

2022-12-05 05:06 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddErrorDialogFragment.kt
> -        requireContext()
ㅋㅋㅋㅋㅋ 구욷

2022-12-05 05:09 UTC, yjooooo requested changes
ToastUtil쓰면 좋을 것 같은 부분 체크했습니다!

2022-12-05 05:09 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/todo/add/AddToDoFragment.kt
> +                        // TODO 확장함수 쓰기
여기 제가 만들어뒀던 ToastUtil 쓰시면 될 것 같아요!

2022-12-05 05:09 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/todo/edit/EditToDoFragment.kt
> +                        Toast.makeText(requireContext(), requireContext().getString(R.string.to_do_duplicate_toast_msg), Toast.LENGTH_SHORT)
여기도요!

2022-12-05 05:10 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/todo/add/AddToDoFragment.kt
> +                        // TODO 확장함수 쓰기
그리고 그냥 getString해도 될겁니다!

2022-12-05 05:22 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/todo/add/AddToDoFragment.kt
> +                        // TODO 확장함수 쓰기
오 굿입니다 👍👍👍

2022-12-07 14:30 UTC, yjooooo approved these changes
고생하셨습니다!!!!!

2022-12-07 15:44 UTC, merged