#151 [fix] 프로필 소개, 프로필 편집 뒤로가기, 회원가입 공개여부 수정
Hous-Release/hous-AOS pull request #160
Opened 2022-12-07 08:20 UTC by 2zerozu

## 관련 이슈
- closed #151

## 작업한 내용
- 프로필 소개, 프로필 편집 뒤로가기, 회원가입 공개여부 수정

## PR 포인트
- 프로필 end 마진 안 걸려서 생겼던 일이었네요 죄송합니다 하하~..
- 편집 안 됐을 때 그거 반영은 다음 이슈에서 ~..

2022-12-07 09:08 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditActivity.kt
> +        )
저는 프로필 수정 뷰에서 수정한 부분이 있을 때에만 뒤로가기가 적용되도록 해야 하는 거로 알고 있습니다..!

2022-12-07 09:09 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditActivity.kt
> +        )
다음 이슈때 해결하려 했는데 ~.. 여기 피알에 반영해볼게요 ㅎㅎ..

2022-12-07 09:09 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditActivity.kt
> +        )
> 저는 프로필 수정 뷰에서 수정한 부분이 있을 때에만 뒤로가기가 적용되도록 해야 하는 거로 알고 있습니다..!

다음 이슈때 해결하려 했는데 ~.. 여기 피알에 반영해볼게요 ㅎㅎ..

2022-12-07 14:03 UTC, murjune requested changes
고생하셨습니다~~  ㅎ ㅎ
addCallback { .. } 로 바꿔주세용~

2022-12-07 14:03 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditActivity.kt
> +                    }.show(supportFragmentManager, WarningDialogFragment.DIALOG_WARNING)
```suggestion
        onBackPressedDispatcher.addCallback{
            WarningDialogFragment().withArgs {
                            putSerializable(
                                WarningDialogFragment.WARNING_TYPE,
                                WarningType.WARNING_EDIT_PROFILE
                            )
                            putParcelable(
                                WarningDialogFragment.CONFIRM_ACTION,
                                ConfirmClickListener(confirmAction = { finish() })
                            )
                        }
                    }.show(supportFragmentManager, WarningDialogFragment.DIALOG_WARNING)
        }
```
- backpressd ktx를 사용해주세요!! 
- 제가 만든 `withArgs` 확장함수도 애용부탁드립니다 ㅋㅋㅋㅋ

2022-12-07 14:40 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditActivity.kt
> +                    }.show(supportFragmentManager, WarningDialogFragment.DIALOG_WARNING)
홍보하는거에서 빵터졌습니다 ㅋㅋㅋㅋㅋㅋㅋㅋ

2022-12-07 14:40 UTC, yjooooo approved these changes
영주고생했어여!!!

2022-12-09 05:17 UTC, murjune approved these changes
일단 어푸어푸어푸로브

2022-12-10 19:51 UTC, KWY0218 approved these changes
LGTM~ 👍

2022-12-10 20:24 UTC, merged