#171 [feat] log event 버튼 심기
Hous-Release/hous-AOS pull request #174
Opened 2022-12-12 14:45 UTC by KWY0218

## 관련 이슈
- closed #171 

## 작업한 내용
- log event 버튼 심기

## PR 포인트
- 일단 제 생각대로 버튼 심었습니다.
- 각 기능마다 커밋 했으니까 시트 확인해서 본인꺼 확인 후 커밋이랑 비교해주세요
- rules, todo-detail, badge, alarm 등 클릭 시 -> 진입으로 소현이랑 얘기 했습니다
- 본인 성향 확인
  - profile 에서 확인하기 + main 에서 본인꺼 클릭 후 확인 하기
  - 이 2개 경우 있어서 main 로직 살짝 수정했습니다. 커밋 내용 봐주세요
- 방 입장하기 empty view는 논의 사항으로 올라가서 그거 빼고 보시면 됩니다~

- apk 자동화 오류 나서 그것도 살짝 수정 완

2022-12-12 19:46 UTC, yjooooo approved these changes
확인 완료했습니다!! 감사합니다!!
수정이 필요한 부분에 ‼️ 표시 달아놨습니다!
[커밋메시지, 구글시트의 EventName, 실제 적용된 것] 3가지를 비교해보며 확인했습니다!

2022-12-12 19:46 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/notification/NotificationActivity.kt
> +        HousLogEvent.enterScreenLogEvent(SCREEN_ALARM, javaClass.name)
연주 - 알림리스트 확인 완!

2022-12-12 19:46 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/withdraw/WithdrawActivity.kt
> +                        clickDateLogEvent(CLICK_WITHDRAW)
연주 - 회원탈퇴하기 확인 완!
**‼️ 커밋메시지에 퇴사하기 -> 탈퇴하기입니다! 확인 부탁드립니다!**

2022-12-12 19:46 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/out_room/OutRoomActivity.kt
> +                    clickDateLogEvent(CLICK_ROOM_OUT)
연주 - 방 퇴사하기 확인 완!
**‼️ 커밋메시지에 로그아웃 -> 퇴사하기입니다! 확인 부탁드립니다!**

2022-12-12 19:46 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/splash/IntroActivity.kt
> +                    enterScreenLogEvent(SCREEN_HOME, MAIN_ACTIVITY_TAG)
‼️홈뷰 진입은 HousFragment의 onViewCreated에 달아줘야할 것 같습니다!
네트워크 에러 이후에도 홈뷰로 이동하는데 이동시키는 함수보다는 홈화면 자체에서 측정하는게 좋을 것 같습니다!

2022-12-12 19:46 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/hous/HousFragment.kt
> +        clickLogEvent(CLICK_HOME_HOMIES)
연주 - 호미카드 클릭 확인 완!

2022-12-12 19:46 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/hous/HousFragment.kt
> +            clickLogEvent(CLICK_BLANK)
연주 - 응원영역 클릭 확인 완!

2022-12-12 19:46 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/hous/HousFragment.kt
> +            clickLogEvent(CLICK_COPY)
연주 - 코드 복사 클릭 확인 완!

2022-12-12 19:46 UTC, yjooooo commented on app/src/main/java/hous/release/android/util/HousLogEvent.kt
> +    const val CLICK_WITHDRAW = "CLICK_SIGN_OUT"
‼️ 저희 코드에서 withdraw == 회원탈퇴 입니다!
로그아웃이랑 헷갈리신 것 같습니다!
구글시트의 EventName과 대조해 보니 회원탈퇴는 서버에서 측정하는 것 같구 로그아웃의 경우를 측정하고 싶었던 것 같은데 로그아웃은 SettingsActivity에 있습니다!! 
<img width="827" alt="image" src="https://user-images.githubusercontent.com/68374234/207139462-038c1970-8268-4fef-98f9-d23245c0a419.png">

2022-12-12 19:47 UTC, yjooooo requested changes
잘못된 부분이 있어서 RequestChange로 수정합니다!

2022-12-13 05:00 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/splash/IntroActivity.kt
> +                    enterScreenLogEvent(SCREEN_HOME, MAIN_ACTIVITY_TAG)
저도 처음에 그렇게 했다가 소현이가 `스플래쉬 타고 메인으로 가는 수` 를 측정하고 싶다고 해서 이렇게 측정했습니당

2022-12-13 05:09 UTC, KWY0218 commented on app/src/main/java/hous/release/android/util/HousLogEvent.kt
> +    const val CLICK_WITHDRAW = "CLICK_SIGN_OUT"
ㅋㅋㅋ이 때 졸면서 해서... 수정했습니다~~

2022-12-13 06:13 UTC, murjune approved these changes
ㅋㅋㅋㅋㅋ 우리꺼까지 다 해주다니 너무 감사합니다 히히  
이 pr 기억해두겠습니다 ㅋㅋㅋㅋ

2022-12-13 06:13 UTC, murjune commented on .github/workflows/Debug_Apk.yml
> +          ${{ runner.os }}-gradle-
그의 땀과 노력..

2022-12-13 06:13 UTC, murjune commented on app/src/main/java/hous/release/android/util/HousLogEvent.kt
> +        if (!BuildConfig.DEBUG) {
배워갑니다 센세!!

2022-12-13 15:34 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/splash/IntroActivity.kt
> +                    enterScreenLogEvent(SCREEN_HOME, MAIN_ACTIVITY_TAG)
아 고렇군요!!! 확인이요!!

2022-12-13 15:43 UTC, yjooooo requested changes
이벤트명 확인 부탁드립니다!! 고생하셨습니다!

2022-12-13 15:43 UTC, yjooooo commented on app/src/main/java/hous/release/android/util/HousLogEvent.kt
> +    const val CLICK_LOG_OUT = "CLICK_LOG_OUT"
<img width="489" alt="image" src="https://user-images.githubusercontent.com/68374234/207377221-109e230d-00f7-4c7e-96f9-b520c677ab20.png">

- 이부분 소현이가 정해준 이벤트명으로 보면 click_sign_out 으로 가야할 것 같아요!
추후에 iOS도 해당 이벤트명으로 로그를 달 것이기 때문에 대소문자도 통일해서 측정해야 AOS, iOS 에서의 이벤트가 하나로 측정됩니다!

- 나머지 이벤트명 모두 소문자로 수정하기 귀찮을 수 있을 것 같은데 그부분은 소현이한테 모두다 대문자로 측정했다고 전달하면 소현이가 안드에 맞춰서 시트 수정해주지 않을까 싶습니다!

2022-12-13 16:20 UTC, murjune requested changes
고생하셨습니다. OurRules 진입하는 부분만 한 번 봐주셔용

2022-12-13 16:20 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/our_rules/main_rule/OurRulesFragment.kt
> +            clickLogEvent(CLICK_RULES_SETTING)
준원 - 세팅 버튼 클릭 확인이요!!

2022-12-13 16:20 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/our_rules/OurRulesActivity.kt
> +        enterScreenLogEvent(SCREEN_RULES, javaClass.name)
![image](https://user-images.githubusercontent.com/87055456/207386093-724a0902-355a-46fb-8c81-462d0a605222.png)
OurRulesActivity가 아닌 HousFragment에 넣어야할 것 같습니다!!

2022-12-14 10:01 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/our_rules/OurRulesActivity.kt
> +        enterScreenLogEvent(SCREEN_RULES, javaClass.name)
@murjune 
`>` 버튼을 클릭한다는 것은 결국 our Rules에 들어가는 것이므로 소현이랑 얘기 후에 our Rules 입장할 때 측정으로 수정했습니다.
혹시 다른 이유가 또 있을까요??

2022-12-14 10:02 UTC, KWY0218 commented
@2zerozu 
@yjooooo 
태그 이름 관련해서는 소현이랑 합의 보겠슴다~

2022-12-15 11:48 UTC, yjooooo approved these changes

2022-12-18 09:40 UTC, merged