#186 Convert to Draft
Hous-Release/hous-AOS pull request #187
Opened 2023-01-17 20:29 UTC by 2zerozu

## 관련 이슈
- closed #186

## 작업한 내용
- 이렇게 하는 게 맞는지 봐주세요..

## PR 포인트
1. HomieProfileViewModel에서

```
_uiState.emit(response)
_uiState.value = _uiState.value.copy(
    birthday = response.birthday.substring(5..9)
)
```
위의 코드처럼 response를 먼저 emit하고 birthday만 따로 copy를 해주는 게 좋을까요?

```
_uiState.value = _uiState.value.copy(
    age = response.age,
    birthday = response.birthday.substring(5..9),
    birthdayPublic = response.birthdayPublic,
    introduction = response.introduction,
.
.
.
)
```
위의 코드처럼 처음부터 copy로 초기화를 하는 게 좋을까요?

2. update 사용해보려고 했는데 제가 원하는대로 쓸 때마다 빨간줄 떠서 사용해보지도 못했네요..
-> `_uiState.update{ }` 이거 맞죠..? 이걸 onSuccess 안에서 사용하는 게 옳은 방법일까요..?

3. 그리고 `_uiState.value = response`와 `_uiState.emit(response)`의 차이를 모르겠습니다..(emit하면 uiState의 모든 관찰자에게 새 이벤트를 알리는 걸로 알고 있습니다.)
-> stateFlow에서는 value에 초기화하는 방식을 사용하지 않나요? 

4. 보니까 액티비티에 있는 collect는 uiState의 변동과 관계 없이 코드가 실행되는 것 같습니다.. (아직 공부를 온전한 게 아니라 이해 못 하고 있는 것 같긴 합니다만..) emit할 때 collect함수가 실행되어야 맞는 거 아닌가Yo..^.ㅜ

2023-01-20 05:18 UTC, KWY0218 requested changes
1.
1과 같은 경우 copy를 통해서 value 값을 바꾸면 emit을 하지 않아도 collect 가 수집하므로 emit은 없어도 된다 생각합니다

2.
[kotlin 문서 참고 ^__^](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/update.html) 
빨간 줄이 뜬거면 잘 못 쓴건데 구글링해서 다시 해보는 것이 어떤지..
onsuccess 에서 쓴다고 빨간줄이 뜨진 않습니다

3. 
emit, value 방식 둘 다 상관 없다고 생각합니다.
다만 emit은 suspend 함수로 coroutine 내에서 stateflow value를 변경시켜야되지만, value는 coroutine이 없어도 value 값을 변경시킬 수 있어서 coroutine 내에 있거나 suspend 내에 있다면 emit도 상관없다고 생각이 듭니다

4. 
어떤 상황인지 자세히 설명점..

2023-01-20 05:18 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/profile/homie/HomieProfileViewModel.kt
> +                    )
지금 emit 후 value 값을 변경해서 collect가 2번 수집할 거 같습니다.
그래서 emit은 없애도 될 것 같습니다.

2023-01-20 14:58 UTC, 2zerozu commented
> 1과 같은 경우 copy를 통해서 value 값을 바꾸면 emit을 하지 않아도 collect 가 수집하므로 emit은 없어도 된다 생각합니다
> 
> 
> [kotlin 문서 참고 ^__^](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/update.html) 빨간 줄이 뜬거면 잘 못 쓴건데 구글링해서 다시 해보는 것이 어떤지.. onsuccess 에서 쓴다고 빨간줄이 뜨진 않습니다
> 
> 
> emit, value 방식 둘 다 상관 없다고 생각합니다. 다만 emit은 suspend 함수로 coroutine 내에서 stateflow value를 변경시켜야되지만, value는 coroutine이 없어도 value 값을 변경시킬 수 있어서 coroutine 내에 있거나 suspend 내에 있다면 emit도 상관없다고 생각이 듭니다
> 
> 
> 어떤 상황인지 자세히 설명점..

emit, value차이 이해했습니다 대단히 감사(__)

1. onSuccess에서 쓴다고 빨간줄이 뜬다는 게 아니라 onSuccess에서는 response를 다뤄야하는데 update는 그 객체 자체를 다뤄서 onSuccess에서 뜨는 게 맞는가~ 물어본 거고, 빨간 줄은 update의 반환형이 객체인 걸 몰라서 일어난 일 ㅎㅎ 감사

4. 기존 코드는 `birthday.substring(5..9)`를 collect 내에서 뷰바인딩 해줬는데, response가 uiState에 저장되기 전에 collect 함수가 실행돼서 birthday가 null인 채로 substring 시도해서 펑~터집니다.. 로그를 찍어봐도 서버통신 직후 response를 저장하기 전에 collect 함수가 실행되더군요 ^.ㅜ

2023-01-21 07:39 UTC, KWY0218 commented
> emit, value차이 이해했습니다 대단히 감사(__)
> 
> 1. onSuccess에서 쓴다고 빨간줄이 뜬다는 게 아니라 onSuccess에서는 response를 다뤄야하는데 update는 그 객체 자체를 다뤄서 onSuccess에서 뜨는 게 맞는가~ 물어본 거고, 빨간 줄은 update의 반환형이 객체인 걸 몰라서 일어난 일 ㅎㅎ 감사
> 2. 기존 코드는 `birthday.substring(5..9)`를 collect 내에서 뷰바인딩 해줬는데, response가 uiState에 저장되기 전에 collect 함수가 실행돼서 birthday가 null인 채로 substring 시도해서 펑~터집니다.. 로그를 찍어봐도 서버통신 직후 response를 저장하기 전에 collect 함수가 실행되더군요 ^.ㅜ

1. `update` 메서드는 `value = value.copy` 를 대체할 수 있는 것이고, response onSuccess 를 통해서 uiState를 변경하므로 상관없다 생각합니다.

2. 지금 에러가 터졌었던 이유가 
1. 초기값으로 빈 문자열이 들어가 있는 `Profile` 설정
2. 초기값 collect 
3. 빈 문자열인데 `subString(5..9)` 에서 5에서 9사이의 문자를 찾고 있어서 펑

이런 순서로 `null` 값이 들어와서 터지는 것이 아닌 빈 문자열인데 5~9번째 사이의 문자를 `substring` 을 해줘서 터지는 에러라고 생각이들고, 
그래서 viewmodel에서 substring 하는 것으로 수정한 거 좋습니다~ 👍

2023-02-08 10:34 UTC, yjooooo approved these changes
고생하셨습니다! 나중에 다시 한번 볼게요!

2023-02-09 08:39 UTC, KWY0218 requested changes
수업 들어가야 되서 일단은 이정도...

2023-02-09 08:39 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/personality/result/PersonalityResultViewModel.kt
> +                    )
```suggestion
                .onSuccess { response ->
                    _uiState.value = response
```
이래도 될 거 같습니다..!

2023-02-09 08:39 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
> +                }
```suggestion
                with(binding) { 
                  if (uiState.profile.introduction.isNullOrEmpty()) {
                        tvProfileIntroduction.setText(R.string.profile_empty_introduction)
                        tvProfileIntroduction.setTextColor(ContextCompat.getColor(requireContext(), R.color.hous_g_4))
                  } else {
                        tvProfileIntroduction.text = uiState.profile.introduction
                        tvProfileIntroduction.setTextColor(ContextCompat.getColor(requireContext(), R.color.hous_g_6))
                  }
                }
```
음 스니펫이 이상하긴 한데 이렇게 if 문 위에다가 with를 1번만 사용할 수 있을 것 같습니다.

2023-02-09 08:39 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/profile/ProfileViewModel.kt
>                      checkTest()
1. 변수 birthday 의 길이가 5 이하일 때 앱이 터지진 않나요??
2. checkTest 변수로 copy를 한번 더 하는 것이 아닌 26-30 line 에서 copy를 할 때 reponse 값을 통해서 isTest도 같이 copy 하면 좋을 것 같습니다

2023-02-09 08:39 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/profile/homie/HomieProfileActivity.kt
> +                    }
요것두 with 2개를 1번으로 줄일 수 있을 것 같은디 의도가 있다면 설명해주세용

2023-02-09 08:39 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/profile/homie/HomieProfileViewModel.kt
> +                    )
이것도 string 길이 4일 때 터질거 같은데...

2023-02-09 08:39 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/tutorial/TutorialViewModel.kt
> +    val isNextBtn = MutableStateFlow(false)
캡슐화를 통해서 외부에서 값을 변경하지 못하도록 해줍시다.
해당 값을 변경하는 건 setter 만들어서 사용하면 될거 같습니다

2023-02-09 08:40 UTC, KWY0218 commented
![image](https://user-images.githubusercontent.com/82709044/217760292-99c55f72-37c4-498b-afc8-1783cba63188.png)
에러 뜨네요 4이하일 때 분기처리 요망

2023-02-09 08:52 UTC, 2zerozu commented
> ![image](https://user-images.githubusercontent.com/82709044/217760292-99c55f72-37c4-498b-afc8-1783cba63188.png)
> 
> 에러 뜨네요 4이하일 때 분기처리 요망

변수 길이가 4 이하로 들어올 리가 없는데도 분기처리 해줘야합니까 ....

2023-02-09 08:56 UTC, KWY0218 commented
> > ![image](https://user-images.githubusercontent.com/82709044/217760292-99c55f72-37c4-498b-afc8-1783cba63188.png)
> > 에러 뜨네요 4이하일 때 분기처리 요망
> 
> 변수 길이가 4 이하로 들어올 리가 없는데도 분기처리 해줘야합니까 ....

아 몰랐티비... 확인~~

2023-02-09 09:03 UTC, KWY0218 commented on app/src/main/java/hous/release/android/util/extension/ContextExtension.kt
> +}
해당 피알에서 안보여서 그러는데 해당 확장함수는 어디서 사용하고 있나요..?

2023-02-10 06:09 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
> +    private fun initUiStateCollect() {
> collect는 계속 수집하는 느낌인데 init을 붙이면 처음 한번만 수집한다는 느낌이 듭니다. 그래서 제 생각은 init을 뺀 collectUiState() 가 적절할 것 같다고 생각하는데 어떻게 생각하시나요..?

확인이요 ~~

2023-02-10 06:12 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/profile/ProfileViewModel.kt
>                      checkTest()
> 1. 변수 birthday 의 길이가 5 이하일 때 앱이 터지진 않나요??
> 2. checkTest 변수로 copy를 한번 더 하는 것이 아닌 26-30 line 에서 copy를 할 때 reponse 값을 통해서 isTest도 같이 copy 하면 좋을 것 같습니다

1. UserInput에서 생년월일을 모두 입력해야 넘어가기 때문에 birthday가 5 이하로 들어올 가능성이 0.01프로라고 생각합니다
2. 확인이욥

2023-02-10 06:13 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/tutorial/TutorialViewModel.kt
> +    val isNextBtn = MutableStateFlow(false)
> 캡슐화를 통해서 외부에서 값을 변경하지 못하도록 해줍시다. 해당 값을 변경하는 건 setter 만들어서 사용하면 될거 같습니다

양방향데바 사용중이라 이렇게 써줬는데 액티비티에서 따로 처리하라는 말인가요?

2023-02-10 06:14 UTC, 2zerozu commented on app/src/main/java/hous/release/android/util/extension/ContextExtension.kt
> +}
> 해당 피알에서 안보여서 그러는데 해당 확장함수는 어디서 사용하고 있나요..?

[432f8c8](https://github.com/Hous-Release/hous-AOS/pull/187/commits/432f8c8d81a13fa2385f4a2d3be3df7c50a9aa53) 여기있습니다요

2023-02-10 06:15 UTC, 2zerozu commented on app/src/main/java/hous/release/android/util/extension/ContextExtension.kt
> +}
> 해당 피알에서 안보여서 그러는데 해당 확장함수는 어디서 사용하고 있나요..?

아 ㅋㅋ.. 추가만 해놓고 반영을 안 해놨네 감사요

2023-02-10 06:20 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/tutorial/TutorialViewModel.kt
> +    val isNextBtn = MutableStateFlow(false)
아 양방향 데바면 음...이렇게 해도 노상관일듯...?

2023-02-11 07:28 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/personality/result/PersonalityResultViewModel.kt
> +                    )
> 이래도 될 거 같습니다..!

<img width="644" alt="image" src="https://user-images.githubusercontent.com/84129098/218246271-45280518-88e2-4a34-aa67-992d1e77c58b.png">
`uiState` 내부의 `personalityResult`에 값 넣어주는 거라 불가피해보이네요 ㅠ

2023-02-11 07:31 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/personality/result/PersonalityResultViewModel.kt
> +                    )
아 타입 확인 잘못했네요 확인이요~~

2023-02-11 07:50 UTC, KWY0218 approved these changes
수고하셨습니다!

2023-02-11 14:21 UTC, murjune approved these changes
굿굿!!

2023-02-11 14:34 UTC, merged