Feature/#205 create design system module
Hous-Release/hous-AOS pull request #206
Opened 2023-05-14 07:14 UTC by KWY0218

## 관련 이슈
- closed #205 

## 작업한 내용
- design system module 생성 및 공통 컴포넌트 구현

## PR 포인트
- 바뀌는 뷰에서 공통으로 사용되는 컴포넌트들을 모듈화 했습니다.
파일을 삭제하고 import 명이 바뀐 것이 많아서 file change가 많다는 점 양해바랍니다 ~ !
사용 방식은 preview 참고해서 사용하면 될 것 같습니다 ~ !

| day | rule slot | homy chip |
| ------- | ------ | ------ |
| ![image](https://github.com/Hous-Release/hous-AOS/assets/82709044/b13d9a7f-f7e4-4e94-aaf2-a20d80acd519) | ![image](https://github.com/Hous-Release/hous-AOS/assets/82709044/5e5d8ca1-1546-47c9-b99e-f72fbb9ffd54) | ![image](https://github.com/Hous-Release/hous-AOS/assets/82709044/d86a3f95-166f-4035-ad7f-c2fb877faef4) |

| tool bar | text field
| ------- | ------ |
| ![image](https://github.com/Hous-Release/hous-AOS/assets/82709044/1a272f12-b46f-419f-bc98-144fe8a509cb) | ![image](https://github.com/Hous-Release/hous-AOS/assets/82709044/091c8a48-f5f7-4942-9904-c7f76bad66bb) |

2023-05-14 14:24 UTC, murjune requested changes
value class 에 관해 논의하고 싶은게 있습니다!
Component화 하느라 고생하셨어유~ 👍

2023-05-14 14:24 UTC, murjune commented on app/build.gradle.kts
> +
👍 👍 👍 👍 👍

2023-05-14 14:24 UTC, murjune commented on designsystem/src/main/java/hous/release/designsystem/component/HomyChip.kt
> +) {
👍 👍  homyTypeOrdinal에 따라 색이 달라지는거였낭

2023-05-14 14:24 UTC, murjune commented on designsystem/src/main/java/hous/release/designsystem/component/HomyChip.kt
> +                    .background(HomyType(homyTypeOrdinal).getColor())
음 맞는거 같구마잉

2023-05-14 14:24 UTC, murjune commented on designsystem/src/main/java/hous/release/designsystem/component/HousTextField.kt
> +            ),
이거 야미야~

2023-05-14 14:24 UTC, murjune commented on designsystem/src/main/java/hous/release/designsystem/constant/HomyType.kt
> +        const val ERROR_MSG = "유요하지 않은 homy type 값입니다."
ㅋㅋㅋㅋ 유요하지 않은?

2023-05-14 14:24 UTC, murjune commented on designsystem/src/main/java/hous/release/designsystem/constant/HomyType.kt
> +        const val ERROR_MSG = "유요하지 않은 homy type 값입니다."
내가 value class를 추천한거긴 한데.. 다시 곰곰히 생각해보니 지금 HomyType는 Mapper의 역할을 하고 있다는 생각이 드네요..
 value class를 사용하는 목적이 특정 data 값을 캡슐화하고 Readable한 단일 값 객체를 만드는 것인데 지금 `HomyType` value class는 단순히 data값을 캡슐화하고 값에 의미를 부여하기 보다는 ordinal number에서 Color값으로 바꾸는 Mapper의 역할을 하고 있다는 생각이 드네용..
 
 그래서 아래와 같은 Mapper class를 만들어서 사용하는건 어떨까유?? 
@KWY0218 
```kotlin

object HomyColorMapper {
    private const val MIN_ORDINAL = 0
    private const val MAX_ORDINAL = 5

    fun getColorBy(ordinal: Int): Color {
        require(ordinal in MIN_ORDINAL..MAX_ORDINAL) {
            "해당 ordinal($ordinal)은($MIN_ORDINAL ~ $MAX_ORDINAL) 내의 숫자가 아닙니다"
        }
        return when (ordinal) {
            0 -> HousYellow
            1 -> HousRed
            2 -> HousBlue
            3 -> HousPurple
            4 -> HousGreen
            else -> HousG3
        }
    }
}
```

2023-05-14 14:24 UTC, murjune commented on designsystem/src/main/java/hous/release/designsystem/theme/Color.kt
> +val HousG4 = Color(0xFFc8c8c8)
Yummy~

2023-05-14 14:39 UTC, KWY0218 commented on designsystem/src/main/java/hous/release/designsystem/constant/HomyType.kt
> +        const val ERROR_MSG = "유요하지 않은 homy type 값입니다."
@murjune 

1. 인정
2. 근데 color mapper 하는 컴포넌트가 homy chip 밖에 사용하지 않기 때문에 
mapper class 말고 HomyChip 파일 내에 private 함수로 만드는 것은 어떤가 합니다.
나중에 다른 곳에서 사용할 수도 있기 때문에 확장성 측면에선 괜찮긴 한데 사용하지 않을 수도 있을 수 있기도 하고,
한군데에서만 사용하는데 object를 만들어야 되나란 생각이 들기 때문입니다...!

2023-05-14 15:02 UTC, murjune commented on designsystem/src/main/java/hous/release/designsystem/constant/HomyType.kt
> +        const val ERROR_MSG = "유요하지 않은 homy type 값입니다."
좋습니다!! 한 곳에서만 사용한다면 굳이? 라는 느낌이 들긴 하네용 
private  함수 좋아용~

2023-05-14 15:03 UTC, murjune approved these changes
어푸어푸 어푸로브

2023-05-14 15:06 UTC, 2zerozu approved these changes
저의 어푸도 가져가실래요?
+) 제목 바꿔놓고 갑니다

2023-05-15 02:10 UTC, yjooooo approved these changes
고생하셨습니다.. 퇴근하면 살펴볼게요 ㅠㅠㅠ

2023-05-15 05:45 UTC, merged