#215 [ui] UI filter bottom sheet
Hous-Release/hous-AOS pull request #216
Opened 2023-05-29 21:02 UTC by KWY0218

## 관련 이슈
- closed #215 

## 작업한 내용
- 필터 바텀시트 구현

## PR 포인트
-

2023-05-30 04:24 UTC, 2zerozu approved these changes
엘지티엠 고생하셨소

2023-05-30 04:24 UTC, 2zerozu commented on feature/todo/src/test/java/hous/release/feature/todo/detail/TodoDetailViewModelTest.kt
> +package hous.release.feature.todo.detail
테코 미쳤다

2023-05-30 05:20 UTC, murjune approved these changes
고생하셨슴당
이따 수업시간에 자세히 봐보게용

2023-05-30 05:20 UTC, murjune commented on feature/todo/src/androidTest/java/hous/release/feature/todo/ExampleInstrumentedTest.kt
> +}
오 안드 테스트도하게?

2023-05-30 05:20 UTC, murjune commented on feature/todo/src/test/java/hous/release/feature/todo/detail/TodoDetailViewModelTest.kt
> +    }
Given When then 으로 하기로 하지않았나용?!

2023-05-30 06:04 UTC, KWY0218 commented on feature/todo/src/androidTest/java/hous/release/feature/todo/ExampleInstrumentedTest.kt
> +}
모듈 만들면 자동으로 생성되는 것입니다~

2023-05-30 06:05 UTC, KWY0218 commented on feature/todo/src/test/java/hous/release/feature/todo/detail/TodoDetailViewModelTest.kt
> +    }
given when then 하기 애매해서 이렇게 했습니다~

2023-05-30 07:35 UTC, murjune requested changes
추가적인 comment 달았습니다!

2023-05-30 07:35 UTC, murjune commented on feature/todo/src/test/java/hous/release/feature/todo/detail/TodoDetailViewModelTest.kt
> +        )
이 부분은 너무 자명한 부분이기 때문에 빼도 괜찮을 것 같습니다.
저는 테스트 코드가 코드의 품질과 신뢰성을 주는 역할도 하지만 설명서 역할도 한다고 생각하기 때문에
불필요한 부분은 빠져야한다고 생각합니당

2023-05-30 07:35 UTC, murjune commented on feature/todo/src/test/java/hous/release/feature/todo/detail/TodoDetailViewModelTest.kt
> +    }
given이 없다면 when, then만 해도 충분할 것 같습니다!
```kotlin
       // when
       todoDetailViewModel.selectDay(0)
        todoDetailViewModel.selectDay(1)
        todoDetailViewModel.selectDay(2)
        // then
        assertAll(
            { assertThat(todoDetailViewModel.isSelectedDay.value[0]).isEqualTo(true) },
            { assertThat(todoDetailViewModel.isSelectedDay.value[1]).isEqualTo(true) },
            { assertThat(todoDetailViewModel.isSelectedDay.value[2]).isEqualTo(true) }
        )

```

2023-05-30 07:35 UTC, murjune commented on feature/todo/src/main/java/hous/release/feature/todo/detail/TodoDetailViewModel.kt
> +    }
이 부분은 getHomies가 아닌 setHomies가 되어야 할 것 같습니다!  
- 이유는 Homie 객체를 SelectableHomy 객체로 매핑 후 homie state에 set해주기 때문입니다

2023-05-30 07:35 UTC, murjune commented on feature/todo/src/test/java/hous/release/feature/todo/detail/TodoDetailViewModelTest.kt
> +    @DisplayName("SelectableHomy 타입으로 매핑한다.")
"getHomies 함수는 Homy 객체를 SelectableHomy 객체로 매핑 후 저장한다" 라는 네이밍은 어떨까요?

2023-05-30 07:35 UTC, murjune commented on feature/todo/src/test/java/hous/release/feature/todo/detail/TodoDetailViewModelTest.kt
> +        )
타입 체크보다는 Selectable List를 만들어서 비교하는 것이 더 좋을 것 같습니다!

2023-05-30 07:35 UTC, murjune commented on feature/todo/src/test/java/hous/release/feature/todo/detail/TodoDetailViewModelTest.kt
> +    }
이 부분도 요일 선택 함수와 동일합니다!

2023-05-31 00:12 UTC, KWY0218 commented on feature/todo/src/main/java/hous/release/feature/todo/detail/TodoDetailViewModel.kt
> +    }
비록 매핑 후 state를 set하긴 하지만 homies의 정보를 서버에서 가져오기 때문에 getHomies 라고 생각합니다...!

2023-05-31 00:14 UTC, KWY0218 commented on feature/todo/src/test/java/hous/release/feature/todo/detail/TodoDetailViewModelTest.kt
> +        )
테스트 의도가 매핑을 검증하는 테스트이기 때문에 타입 체크를 하는 것이 의도가 전달될 것이라고 생각했습니다..!

selectable list를 만든다는 건 for문으로 assert를 하라는 말일까요?!

2023-05-31 10:15 UTC, murjune commented on feature/todo/src/test/java/hous/release/feature/todo/detail/TodoDetailViewModelTest.kt
> +        )
assertThat(todaydetailviewmodel.homies.value).isEquals(listOf<SelectableHomies>(...))

위와같이 비교하는것을 뜻합니다!! 킹틀린 List는 == 비교할 때 객체주소값 비교가 아니라 elements들 비교하는것으로 알고있습니다!!
게다가 elements들도 data class 니까 프로퍼티값을 일일이 비교하겠죵

참고로 ...은 elements들입니당

핸드폰으로 리뷰달아서 문법이 틀릴수도..

2023-05-31 10:22 UTC, murjune commented on feature/todo/src/main/java/hous/release/feature/todo/detail/TodoDetailViewModel.kt
> +    }
음.. 이건 개인차가 있긴하겠지만 보통 함수 premix에 get을 붙이면 리턴값이 있는걸 기대하는데 해당 함수는 호출시에 유스케이스로부터 데이터를 받아와 homies라는 state 변수를 초기화시켜주는 역할을 한다고 생각합니다.

혹시 initHomies() 라는 네이밍은 어떠신가용?? 해당함수는 뷰모델이 생성될 때 homies 변수를 초기화시켜 줄 때 말고 사용안하는것 같슴당

만약 다른곳에서도 해당 함수를 사용한다면 얘기가 달라지겠지만요..🤪

2023-06-01 04:59 UTC, murjune approved these changes
어푸어푸

2023-06-01 05:25 UTC, KWY0218 commented on feature/todo/src/test/java/hous/release/feature/todo/detail/TodoDetailViewModelTest.kt
> +        )
오 처음 알았네요 👍 👍  킹틀린 최고..

2023-06-01 05:27 UTC, KWY0218 commented on feature/todo/src/main/java/hous/release/feature/todo/detail/TodoDetailViewModel.kt
> +    }
![image](https://github.com/Hous-Release/hous-AOS/assets/82709044/111ac80a-28fc-46b8-9d0b-bc63029fa756)

다른 뷰로 갔을 때 초기화라서 onResume 때 통신을 한번 더 하려고 합니다. 그래서 initHomies 는 적절하지 않을 것 같고,

수업시간에 계속 생각해보니까 viewmodel에서 setHomies 좋은 것 같습니다..!
반영하겠습니다 ~ !

2023-06-01 05:45 UTC, murjune reviewed
리뷰확인했슴다 고생했어용~

2023-06-01 05:45 UTC, murjune commented on feature/todo/src/test/java/hous/release/feature/todo/detail/TodoDetailViewModelTest.kt
> +        )
👍👍👍

2023-06-01 05:45 UTC, murjune commented on feature/todo/src/main/java/hous/release/feature/todo/detail/TodoDetailViewModel.kt
> +    private fun setHomies() {
👍👍

2023-06-01 05:52 UTC, merged