#293 [Refactor] image cache
Hous-Release/hous-AOS pull request #297
Opened 2023-08-12 07:57 UTC by murjune

## 관련 이슈
- closed #293 

## 작업한 내용
- 

## PR 포인트
-

2023-08-12 15:50 UTC, KWY0218 requested changes
코맨트 확인하자마자 반영해주세요~!!!

2023-08-12 15:50 UTC, KWY0218 commented on domain/src/main/java/hous/release/domain/entity/Photo.kt
> +}
엉아... s3 주소 build config 로 옮겨줘...

2023-08-13 08:35 UTC, murjune commented on domain/src/main/java/hous/release/domain/entity/Photo.kt
> +}
헉...! 알겠슴니다

2023-08-13 08:57 UTC, murjune commented
`:domain` 에서는 안드로이드 의존성이 없기 때문에 buildConfig를 사용할 수 없어서 다음과 같이 private하게 만들고 가져왔어요!  [9796e1b]  (https://github.com/Hous-Release/hous-AOS/pull/297/commits/9796e1b585b01e75d8f1b217cd48cd576c66c4a2)    

kotlin dsl 에 대해 잘 몰라서 설명은 못하지만.. 빌드할 때  `$buildDir/generated/source/myProperties/HousConfig.kt`을 생성하고 localproperty에 있는 string을 넣는거 같슈

![image](https://github.com/Hous-Release/hous-AOS/assets/87055456/287a7d7b-6c86-4d75-9aba-114cf09ce031)  

![image](https://github.com/Hous-Release/hous-AOS/assets/87055456/a4a57100-be2a-4b21-887d-46fe85278340)

2023-08-13 09:14 UTC, KWY0218 commented
@murjune 
반영 감사합니다 ~ ! domain 에서 build config 작업하기 까다롭지만 불가능 한 건 없네요.. 신기..
그래서 든 생각이 S3 주소가 Domain 모듈에 있는 것이 맞는 것인가..? 란 생각이 듭니다..
해당 URL은 서버 통신을 위한 것이라 Data 모듈 쪽이 더 어울리지 않나란 생각이 듭니다..!
형 생각은 어떤지 궁금합니담

2023-08-13 09:25 UTC, murjune commented
> 그래서 든 생각이 S3 주소가 Domain 모듈에 있는 것이 맞는 것인가..? 란 생각이 듭니다..

그러네용... 그러고보니 해당 객체가 local인지 remote인지 검사하는건 data에서 해야될 것 같습니당..

2023-08-13 10:07 UTC, murjune commented
일단 s3 주소는 삭제하고, 추후에 해당 이미지가 remote인지 local인지 검사하는거를 data 모듈에 옮겨놓도록하겠습니다!

2023-08-13 12:07 UTC, 2zerozu approved these changes
고생하셨습니다~~

2023-08-13 12:07 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/our_rules/model/DetailRuleUiModel.kt
> +data class PhotoUiModel private constructor(
👀👀👀👀

2023-08-14 00:24 UTC, KWY0218 approved these changes
제일 먼저 하기로 꼬옥 약속... 🤙

2023-08-14 10:42 UTC, merged