#32 [feat] 우리집 규칙 추가, 수정, 삭제 뷰로 navigate하는 바텀시트 만들기
Hous-Release/hous-AOS pull request #33
Opened 2022-09-26 13:34 UTC by murjune

## 관련 이슈
- closed #32 

## 작업한 내용
- 우리집 규칙 추가, 수정, 삭제 뷰로 navigate하는 navgraph 속성 추가
- 바텀 시트 UI 만들기
- ourRulesRepositoryImpl 버그 수정
- fragment_our_rule UI 수정

## PR 포인트
- backbutton 누를 때

2022-09-27 01:30 UTC, KWY0218 approved these changes
LGTM 입니당 ^_^

2022-09-27 17:19 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/our_rules/OurRulesFragment.kt
> +        }
반영하겠습니다람쥐~

2022-09-28 13:37 UTC, 2zerozu approved these changes
거대한 Hous 글씨가 눈에 띄네요
LGTN ^______^

2022-09-28 15:57 UTC, yjooooo requested changes
고생하셨습니다!

2022-09-28 15:57 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/our_rules/OurRulesBottomSheetDialogFragment.kt
> +    private val binding get() = _binding ?: error("binding에 null이 들어갔어요~")
이거 에러메시지 제가 string파일에 만들어놨슴다! 그거로 바꿔주시면 좋을 것 같슴다!ㅎㅎㅎ

2022-09-28 15:57 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/our_rules/OurRulesBottomSheetDialogFragment.kt
> +            dialog?.dismiss()
?보다는 requireNotNull이 좀 더 코틀린스럽지 않나 하는 생각이 있습니다!
null일때 바로 익셉션을 내뱉어야 에러 시점을 바로 알 수 있는데 ?는 넘어가니까유?

2022-09-28 15:57 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/our_rules/OurRulesBottomSheetDialogFragment.kt
> +            dialog?.dismiss()
요기도 위에랑 같은 내용입니다!

2022-09-28 15:57 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/our_rules/OurRulesBottomSheetDialogFragment.kt
> +            dialog?.dismiss()
요기도 위에랑 같은 내용입니다!

2022-09-28 15:57 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/our_rules/adapter/OurRulesAdapter.kt
> +    )
이걸 companion object에 빼는게 더 가독성이 좋지 않을까요?

2022-09-28 15:57 UTC, yjooooo commented on app/src/main/java/hous/release/android/util/ItemDiffCallback.kt
> +        onContentsTheSame(oldItem, newItem)
만들어줘서 땡큐!

2022-09-28 16:01 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/our_rules/OurRulesBottomSheetDialogFragment.kt
> +    private val binding get() = _binding ?: error("binding에 null이 들어갔어요~")
반영하겠습니다 ㅎ ㅎ

2022-09-28 16:04 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/our_rules/adapter/OurRulesAdapter.kt
> +    )
오호라 그렇군요~ 가독성 생각은 못했네요 LGTM

2022-09-28 16:07 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/our_rules/OurRulesFragment.kt
> +            ourRulesBottomSheetDialog.show(parentFragmentManager, this.javaClass.name)
헉스.. 이거 원래 생성자에 값 넘기려고 넣었던건데 안지웠었네요 ㅋㅋㅋ 지우도록할게요~!~!

2022-09-28 16:10 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/our_rules/OurRulesBottomSheetDialogFragment.kt
> +            dialog?.dismiss()
let도 null값이 아닐때만 작업을 하기때문에 에러시점을 알 수 없지 않을까요? 사실 여기에 null 값이 들어오면 안되는자리라면 개발자가 qa하는 시점에 알 수 있는게 중요하지 않을까 생각합니다!
@KWY0218 @2zerozu 의견이 궁금합니다!

2022-09-28 16:27 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/our_rules/OurRulesBottomSheetDialogFragment.kt
> +            dialog?.dismiss()
![image](https://user-images.githubusercontent.com/87055456/192834438-e1e3fda4-96ce-4bf3-824b-2e64a816834d.png)  
이렇게 널처리하는 건 어떨까요?!

2022-09-28 16:33 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/our_rules/OurRulesBottomSheetDialogFragment.kt
> +    private val binding get() = _binding ?: error("binding에 null이 들어갔어요~")
저 하나 궁금한게 있는데 string파일에 만들어두신 이유를 알 수 있을까요??  
util패키지에 Constants.kt라는 파일에 넣어두는 건 어떠세요?!

2022-09-28 17:06 UTC, murjune commented
코드리뷰 반영!! thanks to @yjooooo
- NullPointException message도 R.String파일에 추가해뒀습니다!!

2022-09-28 17:52 UTC, yjooooo approved these changes
LGTM

2022-09-28 20:02 UTC, murjune commented
- OurRulesFragment에서 backbutton 로직을 수정했습니다.  
```kotlin
private fun initClickListener() {
        binding.ivMainRuleBackButton.setOnClickListener {
            activity?.finish() ?: Timber.e(getString(R.string.null_point_exception))
        }
```
생각해보니 HouseFragment에서 OurRulesActivity로 navigate하는 것이므로 findNavController().popBackStack() 이 먹질 않습니다

2022-09-28 20:02 UTC, merged