[ui] #5 UserInput 뷰 생성
Hous-Release/hous-AOS pull request #34
Opened 2022-09-26 20:25 UTC by 2zerozu

## 관련 이슈
- closed #이슈넘버

## 작업한 내용
- 

## PR 포인트
-

2022-09-27 01:40 UTC, KWY0218 approved these changes
구현하느라 수고하셨습니다~! ^__^

2022-09-27 01:40 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
> +        }
혹시 TutorialActivity 에 nickname, birthday 정보를 사용하나요???
그것이 아니라면 intent로 넘기는 것 보다 local에 저장하는 로직이 좋을 것 같습니다.
추후에 토큰들 local에 저장할 때 구현하실 때 구현해도 좋을 것 같습니다~

2022-09-27 17:30 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
> +        }
오 그러고보니 nickname이랑 birthday는 프로필 뷰에서도 사용하겠구나  
저도 local에 저장하는거 추천이요~!~!

2022-09-27 17:34 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
> +    }
얘두 Btn보다 Back이 앞에 있었으면 좋겠음 히히

2022-09-27 17:37 UTC, murjune approved these changes
고생하셨습니다 LGTM :D  
함수명에 대한 코멘트를 남겼는데 다들 어떻게 생각하시나요?!

2022-09-28 01:07 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
> +    }
@Hous-Release/android 
이전 로그인 화면에서 finish를 했기 때문에
백버튼을 누르면 로그인 화면으로 가고, 하단에 있는 뒤로가기 버튼을 누르면 앱이 종료될 텐데
백버튼을 누를 때와 뒤로가기 버튼을 누를 때 화면 전환이 달라도 되나요???

2022-09-28 05:27 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
> +    private fun initBtnNextOnClickListener() {
> initNextBtnOnClickListener() 가 더 낫지 않으려낭

btn_next가 id명이라 BtnNext라고 네이밍해봤습니다 희희..

2022-09-28 05:30 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
> +    }
> 얘두initBtnBackOnClickListener() 가 더 낫지 않으려낭 Btn보다 Back이 앞에 있었으면 좋겠음 히히

id명이 btn_back이라서 그렇게 해봤소 수정하겠숩니다 희희

2022-09-28 05:32 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
> +    }
> 혹시 모든 입력을 한 후에 버튼색이 바뀐 후 제가 입력한 것을 지우면 어떻게 되나요?? 버튼 색이 다시 바뀌나요??

아.. 안돌아오네요 수정하겠습니다ㅏ

2022-09-28 05:32 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
> +    }
> observeInputState() 라는 함수명은 어떠세요??

좋아요 감사합니다ㅏ

2022-09-28 05:34 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
> +    }
> @Hous-Release/android 이전 로그인 화면에서 finish를 했기 때문에 백버튼을 누르면 로그인 화면으로 가고, 하단에 있는 뒤로가기 버튼을 누르면 앱이 종료될 텐데 백버튼을 누를 때와 뒤로가기 버튼을 누를 때 화면 전환이 달라도 되나요???

흠 안 될 것 같네요 다시 생각해올게유

2022-09-28 05:35 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
> +    }
> initCheckBtnBirthdayOnClickListener()

네... ㅜㅜ

2022-09-28 05:35 UTC, 2zerozu commented
> 고생하셨습니다 LGTM :D 함수명에 대한 코멘트를 남겼는데 다들 어떻게 생각하시나요?!

조와요 ~

2022-09-28 05:43 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
> +    }
@2zerozu 
이전 로그인에서 userInput으로 갈 때 finish()를 하지말고,
백스택을 클릭하면 finish()를 해서 백스택으로 갈 수 있도록 하면 좋을 것 같습니다.
추후에 메인화면으로 갔을 때 이전 스택들을 전부 날려버리면 괜찮을 것 같습니다

2022-09-28 12:33 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
> +    }
더 좋은것 같습니다 👍 👍

2022-09-28 12:34 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
> +    }
> 오잉 변수명 바뀐게 없는디...?
@KWY0218  initBackBtnOnClickListener() 하핫

2022-09-28 15:59 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
> +        }
@KWY0218  @murjune 저는 유저 개인 정보라고 생각해서 로컬에 저장하는건 위험할 것 같다고 생각하는 입장인데 어떻게 생각하시나요? 이부분은 토큰과 다른 개념이라고 생각합니다!

2022-09-28 16:02 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
> +    private fun initBtnNextOnClickListener() {
저도 initNextBtnOnClickListener 한표요!

2022-09-28 16:08 UTC, yjooooo requested changes
고생하셨습니다!!!

2022-09-28 16:08 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
> +        userInputViewModel.birthday.value = "1999-08-02"
이부분은 나중에 유저에게 받을 부분이니까 뷰모델에 birthday에 박아놓고 수정하는게 좋을 것 같아요! 뷰단에까지 더미를 끌고 올 필요는 없을 것 같습니다!

2022-09-28 16:08 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
> +    }
이전 로그인 액티비티에서 finish()하지 않고 이부분에서는 finish()만해주면 좋을 것 같네요! 
그리고 나중에 회원가입완료되면 그때 앞에 화면들을 날려버리는!

2022-09-28 16:08 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/login/UserInputViewModel.kt
> +    val birthday get() = _birthday
```kotlin
private val _nickname = MutableLiveData<String>()
val nickname: LiveData<String> = _nickname
```
이렇게 타입을 명시해주는게 좋을 것 같아요! 캡슐화 목적으로 나눈거라면 nickname은 mutable한 값이 아니어야하니까요?

2022-09-28 16:09 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/login/UserInputViewModel.kt
> +    val birthday get() = _birthday
이 부분 저도 동의합니다!!

2022-09-28 17:20 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
> +        }
@yjooooo 
음 일단 로컬을 쓰자고 한 계기가
1. 서버에서 유저 정보를 주는지 몰랐음
2. post api 연결이 아닌 putString이라서 서버 연결이 없는 줄 알았음

그리고 로컬에 저장하는 것이 위험한 이유나 잘 나온 아티클 같은게 있을까요??
이 부분은 공부 안 해봐서 몰라서 그럽니다!

2022-10-09 12:14 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/tutorial/TutorialActivity.kt
> +        }.attach()
```suggestion
        TabLayoutMediator(binding.tlTutorialDot, binding.vpTutorial) { tab, _ ->
            tab.view.isClickable = false
        }.attach()
```

2022-10-09 12:35 UTC, yjooooo approved these changes
수고했어요!

2022-10-16 15:00 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
> +        }
@yjooooo @KWY0218 @murjune 이부분 결론이 어떻게 된거죠??

2022-10-16 16:00 UTC, KWY0218 requested changes
작업하시느라 고생하셨습니다!

2022-10-16 16:02 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/tutorial/TutorialViewModel.kt
> +    private val sharedPrefDataSource: SharedPrefDataSource
> ![image](https://user-images.githubusercontent.com/82709044/196045233-58794c58-3b07-4667-8b07-a541444c228d.png)
> 
> 저희는 domain 모듈을 사용하기 때문에 위 그림처럼 presentation 모듈에서 직접 data 모듈을 사용하지 않고, domain 모듈을 사용합니다.
> 
> 따라서 data 모듈 내에 있는 `Authrepositoryimpl` 파라미터에 해당 datasource를 주입하고, 해당 viewmodel에선 authRepository를 주입받는 형식이 자연스러워 보입니다.
> 
> usecase를 만들어서 주입하는 것이 베스트이긴 하나 위에 방식 정도로도 충분할 것 같습니다

아윽 이게 셈나시간에 물어봤던 건데.. 네ㅠ3ㅠ

2022-10-16 17:32 UTC, KWY0218 requested changes
[data layer](https://developer.android.com/jetpack/guide/data-layer?hl=ko) 
한글로 한번 보는걸 추천드립니다..!

2022-10-16 17:32 UTC, KWY0218 commented on data/src/main/java/hous/release/data/repository/AuthRepositoryImpl.kt
> +    override suspend fun initShowTutorial(skipTutorial: Boolean) {
해당 로직은 data source로 다시 옮기고 repository 에선 해당 data source의 메서드를 활용해서 하는 식으로 수정해야된다고 생각합니다...!

2022-10-16 17:32 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/tutorial/TutorialViewModel.kt
> +            _isTutorialState.value = getSkipTutorialUseCase.invoke()
```suggestion
            _isTutorialState.value = getSkipTutorialUseCase()
```
operator fun invoke() 이기 때문에 이렇게 해도 작동이 됩니다

2022-10-16 18:05 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/tutorial/TutorialViewModel.kt
> +            _isTutorialState.value = getSkipTutorialUseCase.invoke()
> operator fun invoke() 이기 때문에 이렇게 해도 작동이 됩니다

이러면 isTutorialState를 nullable하게 바꿔야하네요..

2022-10-17 07:06 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/tutorial/TutorialViewModel.kt
> +            _isTutorialState.value = getSkipTutorialUseCase.invoke()
그건 usecase 때문이 아니라 suspend 함수가 return 값을 가지고 있기 때문이라고 생각이 드는데...
usecase로 바꾸기 전엔 잘 작동이 되었나요??

2022-10-17 08:09 UTC, murjune approved these changes
너무 고생하셨습니당~

2022-10-17 08:09 UTC, murjune commented on data/src/main/java/hous/release/data/datasource/SharedPrefDataSource.kt
혹시 SharedPreference도 Android KTX를 지원해주는 거 알고 계시나요??   
Android KTX를 사용하면 getter, setter를 굳이 안만들어주고, kotlin property를 활용해서 훨씬 간결하게 나타낼 수 있겠습니당   
- 아래 사진은 세미나 과제 할 때 짠 제 코드 입니당 헷 [링크](https://github.com/IN-SOPT-ANDROID/JunWon/blob/develop/view/app/src/main/java/org/sopt/sample/data/local/SoptSharedPreference.kt)
![image](https://user-images.githubusercontent.com/87055456/196120784-6f95681a-dbec-4ce7-bd84-37a45c141bfa.png)

https://developer.android.com/kotlin/ktx?hl=ko

2022-10-17 08:13 UTC, KWY0218 commented on data/src/main/java/hous/release/data/datasource/SharedPrefDataSource.kt
> 근데 세미나 때, dataSource 인터페이스 만든다고 했던거 같은데??

저희 data Source는 인터페이스 안 만들기로 처음에 약속하지 않았나요,,,?

> datasource/local 에다가 SharedPreferDataSource를 넣어주는 건 어떨까요??

👍 

> 아래 사진은 세미나 과제 할 때 짠 제 코드 입니당 헷 [링크](https://github.com/IN-SOPT-ANDROID/JunWon/blob/develop/view/app/src/main/java/org/sopt/sample/data/local/SoptSharedPreference.kt)

쇽

2022-10-17 08:32 UTC, yjooooo requested changes
고생하셨습니다! 저부분 같이 논의해보면 좋을 것 같아요!

2022-10-17 08:32 UTC, yjooooo commented on app/src/main/java/hous/release/android/di/SharedPrefModule.kt
> +    }
@KWY0218 @murjune @2zerozu 
```kotlin
@Module
@InstallIn(SingletonComponent::class)
object LocalPreferencesModule {
    @Provides
    @Singleton
    fun providesLocalPreferences(@ApplicationContext context: Context): SharedPreferences =
        context.getSharedPreferences(context.packageName, Context.MODE_PRIVATE)
}
```
그때 제가 SharedPreferences 주입하는 모듈을 만들자고 했던건 데이터 소스를 주입하는 것이 아니었어요!
현재는 DataSource에서 SharedPreferences를 만들고 있는데 해당 데이터 소스에서만 쓰이는 것이 아닐 수도 있으므로 SharedPreferences를 생성하는 곳이 그곳이면 안될 것 같았어요!
이런식으로 만들면 좋을 것 같은데 어떻게 생각하세요???

2022-10-17 09:11 UTC, murjune commented on app/src/main/java/hous/release/android/di/SharedPrefModule.kt
> +    }
으음 저는 SharedPreferDataSource를 만들고 각자 사용하는 repository에서 SharedPreferDataSource 주입받아서 쓰면 될 것 같다구 생각했는데 별로인가유??  
저희 SharedPreference를 사용하는 곳이 많나요?!

2022-10-17 09:17 UTC, yjooooo commented on app/src/main/java/hous/release/android/di/SharedPrefModule.kt
> +    }
아항 제가 너무 다 분리하려고 한 것 같기도,,,? sharedpreferences를 생성하는 부분이 뭔가 분리됐으면 좋겠다고 생각했었어요 ㅠ

2022-10-17 09:24 UTC, yjooooo commented on app/src/main/java/hous/release/android/di/SharedPrefModule.kt
> +    }
<img width="955" alt="image" src="https://user-images.githubusercontent.com/68374234/196141025-ba6e2d15-de8d-4cdc-b5f5-d26691267168.png">

분리해서 작업해왔던 이유 : 우리는 서버를 하나만 쓰는데 화면, 작업마다 데이터 소스를 나눠놓음. 로컬저장소도 하나의 서버라고 생각하고 화면, 작업마다 나눠놔야하지 않나 하는 생각을 했다!

2022-10-17 18:09 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/tutorial/TutorialViewModel.kt
> +            _isTutorialState.value = getSkipTutorialUseCase.invoke()
> 그건 usecase 때문이 아니라 suspend 함수가 return 값을 가지고 있기 때문이라고 생각이 드는데... usecase로 바꾸기 전엔 잘 작동이 되었나요??

하하 잘 되네요 저 코드 지웠습니다 init만 usecase로 사용해요

2022-10-17 18:09 UTC, 2zerozu commented on data/src/main/java/hous/release/data/repository/AuthRepositoryImpl.kt
> +    override suspend fun initShowTutorial(skipTutorial: Boolean) {
> 해당 로직은 data source로 다시 옮기고 repository 에선 해당 data source의 메서드를 활용해서 하는 식으로 수정해야된다고 생각합니다...!

옙

2022-10-18 06:15 UTC, KWY0218 approved these changes
LGTM 😄

2022-10-18 07:26 UTC, yjooooo commented on app/src/main/java/hous/release/android/di/RepositoryModule.kt
> +import hous.release.domain.repository.*
좋은 리뷰!!!

2022-10-18 07:27 UTC, yjooooo approved these changes
LGTM~!

2022-10-18 08:51 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
> +        }
@KWY0218 이부분 [EncryptedSharedPreferences](https://developer.android.com/topic/security/data?hl=ko) (키를 사용해 암호화한 SharedPreferences) 를 안드로이드에서 제공해주고 있긴 해요,, 근데 제가 이걸 잘 써오다가 API 31이었나 32었나에서 버전 문제가 있어서 다시 SharedPreferences로 돌아왔었거든요,, 그래서 저것을 못쓸거라면 저장을 안하는게 맞다고 생각합니다,, 심지어 이것도 디컴파일이 가능하다는 아티클이 있더라구요,, 그래서 사실상 저희가 앱을 사용하면서 저장하는 정보 온보딩 조회 여부 이런 것들은 사용자의 개인정보가 아니라 괜찮지만 사용자의 개인정보와 관련된 것들은 저장을 안하는게 맞다고 생각합니다! 토큰을 저장하는 것도 민감하지만 그부분은 토큰 만료시간으로 해결법을 보니까요?

👉 [로컬에 저장하는 것이 위험한 것을 보여주는 아티클](https://hyperconnect.github.io/2018/06/03/android-secure-sharedpref-howto.html)

2022-10-18 09:45 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
> +        }
확인 입니다 ~ 설명 감사합니당~ 😄

2022-10-18 12:27 UTC, 2zerozu commented on app/src/main/java/hous/release/android/di/RepositoryModule.kt
> +import hous.release.domain.repository.*
> 나중에 코드를 추적할 때 와일드 카드 import가 있으면 추적이 힘들어질 것 같다는 생각이 듭니다...!
> 
> 
> 
> [wildcard import 없애는 setting](https://blog.leocat.kr/notes/2020/12/14/intellij-avoid-wildcard-imports-in-kotlin-with-intellij) 해당 블로그 참고해서 설정해주시길 바랍니다!!

어 뭐야 왜 이렇게 바꼈냐???

2022-10-18 12:27 UTC, 2zerozu commented on app/src/main/java/hous/release/android/di/RepositoryModule.kt
> +import hous.release.domain.repository.*
> 좋은 리뷰!!! 추적이 힘들기도 하고 무거워지기도 하고

나도 모르는 사이에 저리 변해있구만요
수정하고 올리겠어 ~~

2022-10-18 14:05 UTC, merged