#38 [feat] todo 삭제하기 기능 구현
Hous-Release/hous-AOS pull request #44
Opened 2022-10-03 14:50 UTC by KWY0218

## 관련 이슈
- closed #38 

https://user-images.githubusercontent.com/82709044/193607253-ecff846f-c2e9-4c40-9fea-2d4c9a842d79.mp4

## 작업한 내용
- todo 삭제하기 기능 구현

## PR 포인트
- todo 삭제하기 기능 구현
- main todo Framgnet를 보면 onResume 마다 통신을 하는데 변경 사항이 없어도 통신을 매번 한다는 점이 맘에 안듬..

2022-10-04 14:46 UTC, murjune approved these changes
LGTM ^_^ 일단 나중에 리뷰달아줄게요..

2022-10-05 05:57 UTC, yjooooo requested changes
고생하셨습니다!
?nullable한 값에 대한 처리를 어떻게 해줘야할지 고민이네융

2022-10-05 05:57 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/todo/daily/DailyActivity.kt
> +                bundle.putInt("todoId", todoId)
get할 때도 todoId 키 값을 쓸 것 같은데 companion object에 넣는 것도 좋을 것 같아여!

2022-10-05 05:57 UTC, yjooooo commented on app/src/main/java/hous/release/android/util/TodoBottomSheet.kt
> +        todoId = arguments?.getInt("todoId") ?: 0
요기서 가져오네여 ㅎㅎ 이부분 companion obejct에 const value로 박아서 쓰면 좋을 것 같아여! 여러뷰에서 쓰이니까 하나의 뷰에 박는 게 좀 그렇다면 companion obejct 들만 모아놓는 하나의 클래스파일을 만드는 것도 방법이지 않을까 싶은데 어떻게 생각하시나요?

2022-10-05 05:57 UTC, yjooooo commented on app/src/main/java/hous/release/android/util/TodoDeleteDialog.kt
> +                dialog?.dismiss()
이부분 준원오빠가 했던 것처럼 처리해주는게 좋을 것 같아요!
아마 저 에러메시지는 strings.xml에 있을겁니다!
![image](https://user-images.githubusercontent.com/68374234/193991131-a0a5925d-3fcf-4f18-946a-2de63692ddab.png)

2022-10-05 05:57 UTC, yjooooo commented on app/src/main/java/hous/release/android/util/TodoDeleteDialog.kt
> +            dialog?.dismiss()
이부분 준원오빠가 했던 것처럼 처리해주는게 좋을 것 같아요!
아마 저 에러메시지는 strings.xml에 있을겁니다!
![image](https://user-images.githubusercontent.com/68374234/193991131-a0a5925d-3fcf-4f18-946a-2de63692ddab.png)

2022-10-05 05:57 UTC, yjooooo commented on app/src/main/java/hous/release/android/util/TodoDeleteDialog.kt
> +        dialog?.window?.apply {
요기도? 해줘야하려나 흠,,,

2022-10-07 05:15 UTC, yjooooo approved these changes
고생하셨습니다!

2022-10-07 06:06 UTC, 2zerozu approved these changes
추후에 확인하겠숨다

2022-10-07 07:50 UTC, merged