#41 [feat] 규칙 추가하기 + 뒤로가기 2번할 때 종료
Hous-Release/hous-AOS pull request #51
Opened 2022-10-17 07:03 UTC by murjune

## 관련 이슈
- closed #41 
## 작업 영상
https://user-images.githubusercontent.com/87055456/196112479-85e6f7e4-e3ae-44b3-9819-9462f3d02abf.mp4  

https://user-images.githubusercontent.com/87055456/196112500-96c0baa7-c610-4457-92e3-b740a9e6ab93.mp4  

## 작업한 내용
- 규칙 추가 로직 구현
- 규칙 추가 서버 통신
- 규칙 개수 제한 다이얼로그 
- 규칙 나가기 다이얼로그 
- Rules Navigation 바텀시트 기능구현
- 뒤로가기 2번할 때 종료 로직 구현
- BindingFragment 에서 _binding 변수 protected 접근 제한자 추가
## PR 포인트
- 아 `#41` 붙이는거 까먹었네... 하핫  

## 함께 논의해볼 점  및 궁금한 점
### 1) 규칙 추가 후, 규칙이 바로 업데이트 되지 않는 이슈..
- 규칙을 추가하고, 메인 rule 화면으로 돌아왔을 때, 바로 추가된 규칙이 반영이 되지 않아서 delay(500L)을 준 후 다시 한 번 서버 통신을 하였습니다. 이 부분을 이 방법 외에는 어떻게 할 지.. 모르겠네유  
- 그리고 delay를 몇 초를 줘야 할 지 고민입니당..
- [OurRulesFragment](app/src/main/java/hous/release/android/presentation/our_rules/OurRulesFragment.kt)
```kotlin
    override fun onResume() {
        super.onResume()
        viewLifecycleOwner.lifecycleScope.launch {
            viewModel.getOurRulesInfo()
            delay(500L) // 즉시 반영이 되지 않기 때문에 delay(500L)을 추가했습니다.
            viewModel.getOurRulesInfo()
        }
    }
```
### 2) ~~커스텀 dialog layout~~
<image height = "500" src="https://user-images.githubusercontent.com/87055456/196114817-8203c166-3ab4-4dc0-abbe-a4232bc86693.png" />

- 저는 다이얼로그 `android:layout_width`를 `wrap_content`로 설정했기 때문에, 아래 사진과 같이(연주코드) setLayout 로직을 추가해주지 않았습니다  
- ~~이 부분이 문제가 될까요?!~~ ㅋㅋㅋㅋ 아 문제가 되네요~ 다른 다이얼로그에서도 쑉샥할랬는데.. 흠 바꿀게요~. 

![image](https://user-images.githubusercontent.com/87055456/196115130-18045dcc-ece3-4554-bbab-dfdffa81f55b.png)

### 3) dialog util
```kotlin
fun DialogFragment.initLayout(ratio: Double = 0.82) {
    safeLet(dialog, requireNotNull(dialog).window) { _, window ->
        window.apply {
            isCancelable = false
            setLayout(
                (resources.displayMetrics.widthPixels * ratio).toInt(),
                ViewGroup.LayoutParams.WRAP_CONTENT
            )
            setBackgroundDrawableResource(R.drawable.shape_white_fill_8_rect)
        }
    } ?: Timber.e(
        getString(R.string.null_point_exception_detail_two_item).format(
            "dialog",
            dialog == null,
            "window",
            dialog!!.window == null
        )
    )
}
```
- 아 kdocs 추가할껄... 까먹었다 하하하하ㅏ핳ㅎ
- 다이얼로그 만들 때마다 추가해주기 귀찮아서 util에 initLayout 하나 만들었어요~

2022-10-17 08:36 UTC, KWY0218 requested changes
작업하시느라 수고하셨습니다~!

2022-10-17 08:36 UTC, KWY0218 commented on domain/src/main/java/hous/release/domain/usecase/FetchOurRulesUseCase.kt
> +
하나의 usecase에는 하나의 목적만을 가지고 캡슐화하면 좋을 것 같습니다.
-  `fetchOurRules()` `fetchOurMainRules()` 은 서로 다른 곳에서 사용하는 것 같은데 어디서 어떤 목적인지 파악하기 힘듭니다.
- 그래서 usecase 2개로 나누면 좋을 것 같습니다.

2022-10-17 08:36 UTC, KWY0218 commented on data/src/main/java/hous/release/data/repository/OurRulesRepositoryImpl.kt
> +    }.flowOn(Dispatchers.IO)
[Best practices for coroutines in Android](https://developer.android.com/kotlin/coroutines/coroutines-best-practices#inject-dispatchers) 문서를 보면 dispatcher를 하드코딩 하지 말고 주입을 받아서 넣는 것을 권장하고 있습니다.

제가 이번에 [세미나2 과제](https://github.com/IN-SOPT-ANDROID/wonyong-kang/pull/6/files#diff-3b187dcba4ab880655432a320fe9642876668041817afbff42fe3c13cbda8b9c)에 코루틴 모듈 추가했는데 쇽샥해 주세요 ㅎㅎㅎ

2022-10-17 08:36 UTC, KWY0218 commented on app/src/main/java/hous/release/android/util/extension/DialogFragmentExtension.kt
> +}
`initLayout` 말고 이 메서드의 목적이 담긴 메서드명으로 수정하면 좋을 것 같아요.
이유는 제가 해당 로직을 진짜 모르는데 이 메서드 명을 통해 유추 하려다가 실패했거든요.. ㅎㅎ...

2022-10-17 08:36 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddViewModel.kt
> +    private var tmpId = -1 // 임시로 저장할 id가 필요 -- 서버야 id값 음수로는 안보내지는지 물어봐야함
답변 받으셨나요??

2022-10-17 08:36 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/main/MainActivity.kt
> +    }
뒤로 가기 누르면 토스트 메시지 보여주는 로직인가요??
처음 뒤로가기 버튼을 눌렀을 때 `gap = curTime - onBackPressedTime` 디바운스 시간을 측정하고,
또다시 뒤로가기 버튼을 누르면 해당 시간 차이보다 적으니까 뒤로가기가 된다 
라는 로직이 맞을까요??

처음봐서 신기하네유 👍

2022-10-17 08:37 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddViewModel.kt
> +    private var tmpId = -1 // 임시로 저장할 id가 필요 -- 서버야 id값 음수로는 안보내지는지 물어봐야함
음수 없는걸로 알고있습니다유!

2022-10-17 08:39 UTC, yjooooo commented on app/src/main/java/hous/release/android/util/extension/DialogFragmentExtension.kt
> +}
initLayout이 명시적인 것 같은게,, 정말 다이얼로그의 레이아웃을 초기화해주는 부분이라서 ㅠㅠ

2022-10-17 08:50 UTC, yjooooo reviewed
pr 포인트에 대해 생각을 남겨봤습니다! 고생하셨습니다!

2022-10-17 08:50 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/main/MainActivity.kt
> +    }
```kotlin
    private var backBtnWaitTime = 0L
    private val toast: Toast by lazy { getToast(getString(R.string.main_back_btn_msg)) }

    override fun onBackPressed() {
           //한번더 뒤로가기 눌렀을때 앱꺼지게하는 코드
            if (System.currentTimeMillis() - backBtnWaitTime >= BACK_BTN_WAIT_TIME) {
                backBtnWaitTime = System.currentTimeMillis()
                toast.show()
            } else {
                toast.cancel()
                ActivityCompat.finishAffinity(this)
                System.runFinalization()
                exitProcess(0)
            }
    }
```
이런식으로 구현을 했었는데 onBackPressed를 오버라이드 하지 않은 이유가있을까요??

2022-10-17 08:50 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/our_rules/OurRulesFragment.kt
> +            delay(500L) // 즉시 반영이 되지 않기 때문에 delay(500L)을 추가했습니다.
delay 보다는 추가하는 서버통신의 성공값을 받고나서 추가된 화면으로 이동하면 어떨까요?
성공값 받기 전까지는 로딩창을 보여주고! (로딩 로티는 인영이가 만들어주면 나중에 추가하면 좋을 것 같네여!)
서버한테 추가하고 나서 리스폰스를 넘겨달라고 하구요! 
delay를 지금은 0.5초를 주었지만 저시간보다 더 걸리라는 법이 없으니까요?

2022-10-17 08:50 UTC, yjooooo commented on app/src/main/java/hous/release/android/util/extension/DialogFragmentExtension.kt
> +}
그쵸,, 이게 필요하답니다 ㅋㅋㅋㅋ
다이얼로그 프래그먼트 wrap content로 해도 안먹고 아마 background도 안먹을거기 때문에 뷰가 그려진 시점에 기기 가로값을 받아온 후 레이아웃 설정해줄 필요가 있더라구요 ㅠ

2022-10-17 08:51 UTC, KWY0218 commented on app/src/main/java/hous/release/android/util/extension/DialogFragmentExtension.kt
> +}
다시 올린 pr 설명을 보니 이해가 갔어요.
단순히 initLayout 말고 뭔가 
initLayoutBackground 처럼 background shape를 설정한다는 느낌이 들어가는 메서드 명이면 좋겠는데...
다른분들 생각은 어떤가유..?

아 그러기엔 isCancelable 설정도 하는고만... initLayout 해야허나..?

2022-10-17 08:52 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddViewModel.kt
> +    private var tmpId = -1 // 임시로 저장할 id가 필요 -- 서버야 id값 음수로는 안보내지는지 물어봐야함
아 이거 주석 지워야하는데 까먹었다 ㅋㅋㅋㅋ

2022-10-17 08:56 UTC, murjune commented on domain/src/main/java/hous/release/domain/usecase/FetchOurRulesUseCase.kt
> +
아직 usecase의 역할을 잘 몰라서 이런 실수를 한 것 같습니당.. 감사합니다유~

2022-10-17 08:57 UTC, murjune commented on data/src/main/java/hous/release/data/repository/OurRulesRepositoryImpl.kt
> +    }.flowOn(Dispatchers.IO)
와 저도 저 글 읽었었는데, dispatcher를 어떻게 주입하지??라는 의문만 가지고 있었는데 해소되었네요 개꿀~

2022-10-17 08:57 UTC, murjune commented on data/src/main/java/hous/release/data/repository/OurRulesRepositoryImpl.kt
> +    }.flowOn(Dispatchers.IO)
쑉샥 개꿀~

2022-10-17 08:58 UTC, murjune commented on app/src/main/java/hous/release/android/util/extension/DialogFragmentExtension.kt
> +}
연주 코드봤을 때, initLayout() 함수명 보고 바로 이해가 가서 쑉샥했거든요~!~!  
혹시, 더 좋은 함수명이 있다면 추천해주세유

2022-10-17 08:59 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/main/MainActivity.kt
> +    }
> 뒤로 가기 누르면 토스트 메시지 보여주는 로직인가요??
처음 뒤로가기 버튼을 눌렀을 때 gap = curTime - onBackPressedTime 디바운스 시간을 측정하고,
또다시 뒤로가기 버튼을 누르면 해당 시간 차이보다 적으니까 뒤로가기가 된다
라는 로직이 맞을까요??  

마자유!!

2022-10-17 09:02 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/main/MainActivity.kt
> +    }
> 이런식으로 구현을 했었는데 onBackPressed를 오버라이드 하지 않은 이유가있을까요??  

onbackpressed 오버라이딩 하는 방식이 api 33부터 deprecated 되었기 때문이에요 ㅜㅜ  
그래서 onBackPressedDispatcher를 사용해서 백 버튼 로직을 짜야합니다  

https://developer.android.com/guide/navigation/navigation-custom-back

2022-10-17 09:02 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/our_rules/OurRulesFragment.kt
> +            delay(500L) // 즉시 반영이 되지 않기 때문에 delay(500L)을 추가했습니다.
> delay를 지금은 0.5초를 주었지만 저시간보다 더 걸리라는 법이 없으니까요?  
마자요.. 진짜 이렇게 하면 안되는데 ㅜ

2022-10-17 09:05 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/main/MainActivity.kt
> +    }
오 몰랐던 사실 너무 유익해!!! 고마워유 ㅎㅎㅎ

2022-10-17 09:07 UTC, murjune commented on app/src/main/java/hous/release/android/util/extension/DialogFragmentExtension.kt
> +}
헤헷.. 좋은 가르침 감사합니당

2022-10-17 09:15 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/our_rules/OurRulesFragment.kt
> +            delay(500L) // 즉시 반영이 되지 않기 때문에 delay(500L)을 추가했습니다.
response 넘겨주는 시점이면 db는 업데이트 된다고 하니 그 시점만 처리하면될 것 같아요!

2022-10-17 09:15 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/our_rules/OurRulesFragment.kt
> +            delay(500L) // 즉시 반영이 되지 않기 때문에 delay(500L)을 추가했습니다.
204 -> 201로 변경되어 해결 가능으로 논의 완료!

2022-10-17 09:40 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/our_rules/OurRulesFragment.kt
> +            delay(500L) // 즉시 반영이 되지 않기 때문에 delay(500L)을 추가했습니다.
야아호~~~~

2022-10-17 12:32 UTC, KWY0218 commented on app/src/main/java/hous/release/android/util/extension/DialogFragmentExtension.kt
> +}
딱히 생각나는게 없어서 initLayout 기....

2022-10-17 15:52 UTC, 2zerozu approved these changes
고생하셨습니다ㅏ

2022-10-17 15:52 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/main/MainActivity.kt
> +    }
쇽샥 해갑니다 감사감사

2022-10-17 19:05 UTC, 2zerozu commented on app/src/main/res/values/strings.xml
> +    <string name="finish_app_toast_msg">\'뒤로\'버튼을 한 번 더 누르시면 종료됩니다</string>
뒤로가기를 한 번 더 누르시면 앱이 종료돼요! 입니다ㅏ

2022-10-18 07:56 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/our_rules/OurRulesFragment.kt
> +            delay(500L) // 즉시 반영이 되지 않기 때문에 delay(500L)을 추가했습니다.
@murjune 이부분 수정하시면 카톡으로 한번 알려주세요 approve하겠습니다~!

2022-10-18 16:37 UTC, KWY0218 approved these changes
LGTM 😄

2022-10-18 16:37 UTC, KWY0218 commented on app/src/main/java/hous/release/android/di/RetrofitModule.kt
> +import java.util.concurrent.*
나중에 코드를 추적할 때 와일드 카드 import가 있으면 추적이 힘들어질 것 같다는 생각이 듭니다...!

[wildcard import 없애는 setting](https://blog.leocat.kr/notes/2020/12/14/intellij-avoid-wildcard-imports-in-kotlin-with-intellij) 해당 블로그 참고해서 설정해주시길 바랍니다!!

2022-10-18 16:41 UTC, KWY0218 commented on domain/src/main/java/hous/release/domain/usecase/GetOurMainRulesUseCase.kt
> +    private val defaultDispatcher: CoroutineDispatcher
Dispatcher 주입 어떻게 된거지ㅋㅋㅋ 신기하네...

2022-10-18 20:02 UTC, murjune commented on domain/src/main/java/hous/release/domain/usecase/GetOurMainRulesUseCase.kt
> +    private val defaultDispatcher: CoroutineDispatcher
되겠냐고~ 안됩니다 ㅋㅋㅋㅋㅋㅋ 삭제했어요

2022-10-18 20:03 UTC, murjune commented on app/src/main/res/values/strings.xml
> +    <string name="finish_app_toast_msg">\'뒤로\'버튼을 한 번 더 누르시면 종료됩니다</string>
바꿀게유~

2022-10-18 20:04 UTC, murjune commented on app/src/main/java/hous/release/android/di/RetrofitModule.kt
> +import java.util.concurrent.*
헤헤 알겠습니닷

2022-10-18 20:20 UTC, murjune commented on domain/src/main/java/hous/release/domain/usecase/GetOurMainRulesUseCase.kt
> +    private val defaultDispatcher: CoroutineDispatcher
# 어제 화제였던 준원's BUG
## 수정 전
```kotlin
private fun initSaveButtonListener() {
        binding.ivAddRuleSaveButton.setOnClickListener {
                viewModel.putAddRuleList() // 얘가 아직 작업 수행 다 하지도 않았는데
                findNavController().popBackStack() // 얘가 실행이 되버린 거임.. 그래서 ViewModel cleared()호출돼서 JobCancellExeption이 떴다~
        }
    }
```
## 수정 후
```kotlin
private fun initSaveButtonListener() {
        binding.ivAddRuleSaveButton.setOnClickListener {
            viewLifecycleOwner.lifecycleScope.launch {
                viewModel.putAddRuleList().join() // 해결 ^__^
                findNavController().popBackStack()
            }
        }
    }
```

2022-10-18 20:20 UTC, murjune commented
# 어제 화제였던 준원's BUG
## 수정 전
```kotlin
private fun initSaveButtonListener() {
        binding.ivAddRuleSaveButton.setOnClickListener {
                viewModel.putAddRuleList() // 얘가 아직 작업 수행 다 하지도 않았는데
                findNavController().popBackStack() // 얘가 실행이 되버린 거임.. 그래서 ViewModel cleared()호출돼서 JobCancellExeption이 떴다~
        }
    }
```
## 수정 후
```kotlin
private fun initSaveButtonListener() {
        binding.ivAddRuleSaveButton.setOnClickListener {
            viewLifecycleOwner.lifecycleScope.launch {
                viewModel.putAddRuleList().join() // 해결 ^__^
                findNavController().popBackStack()
            }
        }
    }
```

2022-10-19 06:02 UTC, yjooooo approved these changes
수정사항에 NoDataResponse 가 왜 없나 했더니 제가 예전에 넣어놨었네요? ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
한달동안 수고하셨습니다!!!

2022-10-19 09:44 UTC, merged