#53 [ui, feat] to do 개수 초과시 다이얼로그 구현
Hous-Release/hous-AOS pull request #63
Opened 2022-10-21 02:12 UTC by KWY0218

## 관련 이슈
- closed #53 

## 작업한 내용
![KakaoTalk_20221021_111141176](https://user-images.githubusercontent.com/82709044/197095068-927f43fd-eed5-41bb-b631-5e6c86a95b4c.jpg)

- to do 개수 초과시 다이얼로그 구현

## PR 포인트
- `initLayout` 확장함수 이거 좋네요 👍 
- 전에 준원이형 에러잡을 때 가져왔던 55번 브랜치에 작업 해버렸네요..
- 그래도 풀 받고 해서 문제는 없어 보이네요... 주의하겠습니다.. 😭

2022-10-21 02:52 UTC, 2zerozu approved these changes
고생하셨습니다 야미

2022-10-21 02:52 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/todo/detail/TodoLimitDialog.kt
> +class TodoLimitDialog : DialogFragment() {
다이얼로그 이제 참고할 때가 돼서 잘 보고갑니다

2022-10-21 02:52 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/todo/detail/daily/DailyFragment.kt
> +                    TodoLimitDialog().show(parentFragmentManager, this.javaClass.name)
이거도 나중에 참고할게용

2022-10-21 07:12 UTC, murjune reviewed
LGTM ^__^

2022-10-21 07:12 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/todo/detail/TodoLimitDialog.kt
> +        initLayout()
헷 맛있지~?~?

2022-10-21 07:12 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/todo/detail/daily/DailyFragment.kt
> +                    TodoLimitDialog().show(parentFragmentManager, this.javaClass.name)
ChildFragmentManager로 바꿔줘유~

2022-10-21 07:12 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/todo/detail/member/MemberFragment.kt
> +                    TodoLimitDialog().show(parentFragmentManager, this.javaClass.name)
얘두~

2022-10-21 07:14 UTC, murjune approved these changes
Approve~

2022-10-21 07:16 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/todo/detail/TodoLimitDialog.kt
> +        initLayout()
더~주~세~요~

2022-10-22 16:54 UTC, yjooooo requested changes
고생하셨어유~~~

2022-10-22 16:54 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/todo/detail/TodoLimitDialog.kt
> +class TodoLimitDialog : DialogFragment() {
후 다행이다 WarningDialog가 아니군 ㅎㅎㅎㅎ

2022-10-22 16:54 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/todo/detail/TodoLimitDialog.kt
> +        }
이부분 dismiss()로도 처리가 되는데!
@murjune 생각해보니 준원오빠 코드에도 있었던 것 같은데!

2022-10-22 16:58 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/todo/detail/TodoLimitDialog.kt
> +        }
@yjooooo 
이 부분 todo 삭제 다이얼로그를 Warning Dialog 로 이전하면서 수정할게요~!!

2022-10-22 17:01 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/todo/detail/TodoLimitDialog.kt
> +        }
아 넵넵!!!

2022-10-22 17:04 UTC, yjooooo approved these changes
GOOD

2022-10-23 16:19 UTC, merged