#74 [ui/feat] UserInput 데이트피커 구현
Hous-Release/hous-AOS pull request #82
Opened 2022-10-25 16:01 UTC by 2zerozu

## 관련 이슈
- closed #74

Uploading 화면 기록 2022-10-26 오전 12.53.40.mov…

![스크린샷 2022-10-26 오전 12 56 20](https://user-images.githubusercontent.com/84129098/197823852-4edc420e-efb1-4a7b-b866-318471db2491.png)
-> 정상 로그인 경로를 거치지 않고 UserInput에서 액티비티 시작해서 다음으로 눌러도 넘어가지 않지만 request 잘 보내고 있는 거 확인했습니다

## 작업한 내용
- 데이터피커 ui 구현
- 데이터피커 "ㅇㅇㅇㅇ-ㅇㅇ-ㅇㅇ"형식으로 변경 로직

## PR 포인트
- 데이트피커..?

2022-10-26 00:33 UTC, KWY0218 reviewed
작업하시느라 수고하셨습니다..!
혹시 단톡방에 올라온 데이트 피커 2개 중 영어로 된 데이트 피커로 결정된 것인가요??

2022-10-26 00:33 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/login/DatePickerDialog.kt
> +    }
```suggestion
    private fun getMonthFormat(month: Int): String = "%02d".format(month+1)
```
format을 사용해서 코드를 더 줄일 수 있을 거 같습니다

2022-10-26 00:33 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/login/DatePickerDialog.kt
> +    }
```suggestion
    private fun getDayFormat(day: Int): String = "%02d".format(day)
```
여기두

2022-10-26 00:33 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/login/DatePickerDialog.kt
> +        initLayout()
`onStart` 에 initLayout을 한 이유가 있을까요??

2022-10-26 01:22 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/login/DatePickerDialog.kt
> +    }
영어로 세팅한 사람들도 있을 것 같아 디자인 수정하였습니다
(년/월/일 선 길이가 일정해짐)

2022-10-26 01:26 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/login/DatePickerDialog.kt
> +        initLayout()
`onViewCreated`에다가 했어야했는데 실수네요 수정하겠습니당

2022-10-26 01:27 UTC, 2zerozu commented
> 작업하시느라 수고하셨습니다..! 혹시 단톡방에 올라온 데이트 피커 2개 중 영어로 된 데이트 피커로 결정된 것인가요??

영어로 세팅한 사람들도 있을 것 같다고 하여 디자인 수정하였습니다
(년/월/일 선 길이가 일정해짐)

2022-10-26 08:42 UTC, yjooooo requested changes
고생하셨습니다!

2022-10-26 08:46 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/login/DatePickerDialog.kt
> +class DatePickerDialog(private val doAfterConfirm: (date: String) -> Unit) :
> 제가 그때 데이트피커 자료 공유하면서 생성자로 넘기는 부분은 바꿔야한다고 말했는데 이부분 그 WarningDialogFragment에 넘기는 것처럼 confirmClickListener를 parcelable로 argument로 넘겨주세요! 사용법은 슬랙이랑 이전 pr에 있는데 모르겠으면 물어봐도 조하여!

해볼게요~~ 감삼당

2022-10-27 17:14 UTC, yjooooo approved these changes
GOOOOOOD!!!!!

2022-10-27 17:19 UTC, KWY0218 approved these changes
GOOOOOOOD ~ 👍

2022-10-27 17:37 UTC, murjune approved these changes
고생하셨습니다~!~! 저 질문하나 남겼는데 답변부탁드립니당

2022-10-27 17:37 UTC, murjune commented on app/src/main/java/hous/release/android/util/dialog/DatePickerDialog.kt
> +    }
onCreateDialog?? 처음보네요 ㄷ ㄷ  
 왜 여기서  inflate시켜주고 로직이 여기서 처리가 되는건가유??  
@yjooooo

2022-10-27 17:37 UTC, murjune commented on app/src/main/java/hous/release/android/util/dialog/DatePickerClickListener.kt
> +}
👍 👍 👍

2022-10-27 17:46 UTC, murjune commented on app/src/main/java/hous/release/android/util/dialog/DatePickerDialog.kt
> +    }
답변 감사합니다 :D

2022-10-27 17:52 UTC, merged