Feature/#88 set profile api
Hous-Release/hous-AOS pull request #90
Opened 2022-10-27 19:12 UTC by 2zerozu

## 관련 이슈
- closed #이슈넘버

## 작업한 내용
- 

## PR 포인트
-

2022-10-27 22:14 UTC, KWY0218 requested changes
서버통신 수고하셨습니다~ 👍 
viewmodel 로직 리뷰는 리소스들이 전부 나온 후에 올라온 PR에서 하겠습니다 ~ !

2022-10-27 22:14 UTC, KWY0218 commented on data/src/main/java/hous/release/data/entity/response/ProfileResponse.kt
> +    val testScore: Profile.TestScore
선생님 귀찮아도 TestScore data entity도 만드셔야 합니다 ^__^

2022-10-27 22:14 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/profile/ProfileViewModel.kt
> +            _isTest.value = _profileData.value!!.testScore != Profile.TestScore(0, 0, 0, 0, 0)
이 함수는 안 쓰는 것 같은데 isTest 변수가 잘 작동이 되는 것인가요?

2022-10-27 22:14 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
> +                val profileSet = getProfileSet(it.personalityColor)
`getProfileSet` 은 추후에 없어지는 것이죠??

2022-10-28 04:21 UTC, 2zerozu commented on data/src/main/java/hous/release/data/entity/response/ProfileResponse.kt
> +    val testScore: Profile.TestScore
> 선생님 귀찮아도 TestScore data entity도 만드셔야 합니다 ^__^

로그인에서 이렇게 했는데 아무도 뭐라 안 해서 .... 예 ......

2022-10-28 04:22 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
> +                val profileSet = getProfileSet(it.personalityColor)
> `getProfileSet` 은 추후에 없어지는 것이죠??

로티 받으면 그 때 생각해보려구요 ㅎ

2022-10-28 10:21 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/profile/ProfileViewModel.kt
> +            _isTest.value = _profileData.value!!.testScore != Profile.TestScore(0, 0, 0, 0, 0)
> 이 함수는 안 쓰는 것 같은데 isTest 변수가 잘 작동이 되는 것인가요?

호출을 안 해줬네 바보...

2022-10-28 11:24 UTC, murjune approved these changes
서버통신 수고하셨습니다~ 👍

2022-10-28 13:02 UTC, KWY0218 approved these changes

2022-10-28 13:02 UTC, KWY0218 commented on data/src/main/java/hous/release/data/entity/response/ProfileResponse.kt
> +        personalityColor = this.personalityColor,
이 부분을 enum class로 바꾸는 것 어떨까요?

2022-10-28 16:54 UTC, yjooooo approved these changes
고생하셨습니다! 어제 같이 개발해줘서 땡큥

2022-10-28 16:54 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
> +    private fun getProfileSet(colorType: String): ProfileSet {
bindingadpater 만들어놔서 이부분 바꾸셔도 좋을 것 같아요 ㅎㅎ

2022-10-28 16:54 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/profile/ProfileViewModel.kt
> +                    _profileData.value = it
it 보다는 user로 명시해주면 어떨까용?

2022-10-28 18:45 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
> +    private fun getProfileSet(colorType: String): ProfileSet {
> bindingadpater 만들어놔서 이부분 바꾸셔도 좋을 것 같아요 ㅎㅎ

네 ~~

2022-10-28 18:46 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/profile/ProfileViewModel.kt
> +                    _profileData.value = it
> it 보다는 user로 명시해주면 어떨까용?

확인입니다요!! `result`는 어때요?

2022-10-28 22:53 UTC, merged