#78 [feat/ui] 규칙 삭제 뷰/ 기능/ 서버 통신
Hous-Release/hous-AOS pull request #91
Opened 2022-10-27 22:07 UTC by murjune

## 관련 이슈
- closed #78 

## 작업한 내용
- 규칙 삭제 뷰 
- 규칙 삭제 기능 구현
- 규칙 서버 통신 
- onBackpressedCallback 할당 해제 로직 수정
- 규칙 추가뷰에서 이탈 다이얼로그 -> 유틸 다이얼로그로 수정~
## PR 포인트
-

2022-10-27 22:43 UTC, KWY0218 reviewed
어우 앱잼 때 규칙 추가 했던게 떠오르네요 ^__^;;;
작업하시느라 고생하셨습니다~~! 😄

2022-10-27 22:43 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/our_rules/adapter/OurRulesDeleteAdapter.kt
> +            binding.data = data
이 부분은 왜 with 내에 안 들어간 이유가 있을까요?

2022-10-27 22:43 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddFragment.kt
> +                (binding.rvAddOurRules.adapter as OurRulesAddAdapter).submitList(uiState.ourRuleList)
어처피 무조건 초기화 되지만,
위 adapter nullable이라 null 처리 해야 된다고 하네요
그래서 `requireNotNull` 사용해서 에러 메시지 출력까지 추가하면 좋을 것 같습니다

2022-10-27 22:43 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddFragment.kt
> +        }.also { callback -> onBackPressedCallback = callback }
저 로직 이해가 잘 안되는데, onBackPressedCallback을 callback으로 초기화 하셨는데 
onBackPressedCallback는 언제 어디서 쓰는 거죠???

2022-10-27 22:43 UTC, KWY0218 commented on app/src/main/java/hous/release/android/presentation/our_rules/delete_rule/OurRuleDeleteViewModel.kt
> +    private val mRulesIdHashMap by lazy { mutableMapOf<Int, Boolean>() }
init 때 바로 초기화가 되는데 lazy 하게 만들 필요가 있나요??
이거 때문에 require not null 계속 사용하게 되는 것 아닌가요??

2022-10-27 22:43 UTC, KWY0218 commented on data/src/main/java/hous/release/data/repository/OurRulesRepositoryImpl.kt
> +) : OurRulesRepository {
dispatcher 모듈이 없으면 의존성 주입이 안된다는 말이 이해가 안됩니다..!
dispatcher 모듈 없애도 파라미터 디폴트 값으로 이런식으로 넣어주면 iodispatcher 사용할 수 있지 않나요??

2022-10-27 22:43 UTC, KWY0218 commented on data/src/main/java/hous/release/data/service/OurRulesService.kt
> +    suspend fun deleteRuleContent(@Body body: DeleteRulesRequest): NoDataResponse
[BODY 유무](https://whale-order.tistory.com/3) 따라서 안되는 거 처음 알았네요..!!

2022-10-28 08:00 UTC, murjune commented on data/src/main/java/hous/release/data/repository/OurRulesRepositoryImpl.kt
> +) : OurRulesRepository {
그니깐유.. 왜 안될까요??  
계속 힐트오류가 생기더라구요

2022-10-28 08:03 UTC, murjune commented on data/src/main/java/hous/release/data/service/OurRulesService.kt
> +    suspend fun deleteRuleContent(@Body body: DeleteRulesRequest): NoDataResponse
그니까요.. 진짜 삽질 겁나 했답니다 ㅜㅜ

2022-10-28 08:06 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddFragment.kt
> +        }.also { callback -> onBackPressedCallback = callback }
OndestroyedView에서 onBackpressedCallback을 remove해줍니다!!  
해당 콜백을 끝날때 지워주지않으면 다른 프래먼트에서도 백버튼 눌렀을 때 해당 콜백이 실행돼서 앱이 터집니당

2022-10-28 08:15 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/our_rules/delete_rule/OurRuleDeleteViewModel.kt
> +    private val mRulesIdHashMap by lazy { mutableMapOf<Int, Boolean>() }
![image](https://user-images.githubusercontent.com/87055456/198538346-7f2a46ae-e969-457f-8f47-fb2259240b68.png)  

map은 `get`해 올 때 value값이 nullable하기 때문에 항상 널처리를 해줘야합니당  

> init 때 바로 초기화가 되는데 lazy 하게 만들 필요가 있나요??  

아 그러네.. 바본가..?? 수정할게여

2022-10-28 08:19 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/our_rules/adapter/OurRulesDeleteAdapter.kt
> +            binding.data = data
dataBinding이랑 ViewBinding해주는 부분을 구분하고 싶었달까..?? ㅋㅋㅋㅋ

2022-10-28 08:30 UTC, KWY0218 approved these changes
LGTM ~ 👍

2022-10-28 12:57 UTC, 2zerozu approved these changes
잘 보고갑니다 LGTM !!!!

2022-10-28 12:57 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/our_rules/adapter/OurRulesDeleteAdapter.kt
> +        if (!::inflater.isInitialized) inflater = LayoutInflater.from(parent.context)
😮

2022-10-28 12:57 UTC, 2zerozu commented on app/src/main/java/hous/release/android/presentation/our_rules/delete_rule/OurRuleDeleteFragment.kt
> +            findNavController().popBackStack()
이제 프래그먼트 늪 속에 빠질 예정인데 보고갑니다 @_@

2022-10-28 12:57 UTC, 2zerozu commented on data/src/main/java/hous/release/data/repository/OurRulesRepositoryImpl.kt
> +) : OurRulesRepository {
@_@

2022-10-28 12:57 UTC, 2zerozu commented on data/src/main/java/hous/release/data/service/OurRulesService.kt
> +    suspend fun deleteRuleContent(@Body body: DeleteRulesRequest): NoDataResponse
배워갑니다ㅏ

2022-10-28 17:03 UTC, yjooooo requested changes
규칙 부분 구현하시느라 힘드셨을텐데 고생하셨습니다!

2022-10-28 17:03 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddFragment.kt
> +            adapter = OurRulesAddAdapter()
OurRulesAddAdapter를 아래처럼 전역변수로 생성해주면 위에 Line55에서 ourRulesAddAdapter만 써주면 되어서 더 직관적이라고 생각합니다!
```kotlin
private val ourRulesAddAdapter = OurRulesAddAdapter()
```

2022-10-28 17:03 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/our_rules/delete_rule/OurRuleDeleteFragment.kt
> +                requireNotNull(binding.rvDeleteOurRules.adapter as? OurRulesDeleteAdapter) {
여기도요!!!

2022-10-28 17:03 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/our_rules/edit_rule/OurRuleEditFragment.kt
> +                requireNotNull(binding.rvEditOurRules.adapter as OurRulesEditAdapter) { getString(R.string.null_point_exception) }.submitList(
여기도!

2022-10-28 18:36 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/our_rules/edit_rule/OurRuleEditFragment.kt
> +                requireNotNull(binding.rvEditOurRules.adapter as OurRulesEditAdapter) { getString(R.string.null_point_exception) }.submitList(
넵넵!!

2022-10-28 18:36 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/our_rules/delete_rule/OurRuleDeleteFragment.kt
> +                requireNotNull(binding.rvDeleteOurRules.adapter as? OurRulesDeleteAdapter) {
넵넵!!

2022-10-28 18:37 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddFragment.kt
> +                requireNotNull(binding.rvAddOurRules.adapter as? OurRulesAddAdapter) {
으...악..

2022-10-28 18:37 UTC, murjune commented on app/src/main/java/hous/release/android/presentation/our_rules/adapter/OurRulesDeleteAdapter.kt
> +            }
알겠습니다 ㅎ ㅎ ㅎ

2022-10-29 00:37 UTC, yjooooo commented on app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddFragment.kt
> +                requireNotNull(binding.rvAddOurRules.adapter as? OurRulesAddAdapter) {
ㅜㅜㅜ

2022-10-29 00:38 UTC, yjooooo approved these changes
고생하셨습니다!!!!

2022-10-29 06:42 UTC, merged